### ISSUE TITLE
Creating a new source version causes concepts to completely crap out

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/oclapi#116]
I created a new version of the CIEL source:

```
POST http://api.openconceptlab.org/orgs/CIEL/sources/CIEL/versions/
{
    "id": "0.9",
    "released": "true",
    "description": "pre-release version"
}
```

I then tried grabbing concepts the new CIEL version and then from the latest version of CIEL and both returned zero concepts (note that both of these worked correctly before creating the new source version):

```
GET http://api.openconceptlab.org/orgs/CIEL/sources/CIEL/v0.9/concepts/
GET http://api.openconceptlab.org/orgs/CIEL/sources/CIEL/concepts/
```

Also, requesting specific concepts from latest or v0.9 also fails:

```
GET http://api.openconceptlab.org/orgs/CIEL/sources/CIEL/concepts/1002/
GET http://api.openconceptlab.org/orgs/CIEL/sources/CIEL/v0.9/concepts/1002/
```

However, the concepts are still returned when I explicitly include the "latest" source version, using the global concept search, or requesting an individual concept with the latest source version:

```
GET http://api.openconceptlab.org/orgs/CIEL/sources/CIEL/55497986525c3173c33d2c4a/concepts/
GET http://api.openconceptlab.org/concepts/
GET http://api.openconceptlab.org/orgs/CIEL/sources/CIEL/55497986525c3173c33d2c4a/concepts/1002/
```

This same behavior occurred several weeks ago. We assumed that the index got corrupted so PK rebuilt the index but unfortunately it did not correct the issue. We were forced to wipe the server.

**Comment by afernandes-carecloud** [comment]
@paynejd , are those the only attributes you specified in your call to create a new source version?  If you want your new version to inherit concepts/mappings from an existing one, you have to specify the existing one as 'previous_version_mnemonic' or 'parent_version_mnemonic'.

**Comment by paynejd** [comment]
@MisterNando Yes, those were the only attributes I used. I actually had not intended (when I wrote the spec) that the previous / parent were anything more than descriptive or that they would influence the meaning of the underlying data in any way, but that is potentially really useful if they do.

Can you just provide a short description of how you implemented this, so that I can better understand it and write it into the spec? I'll re-test with one of those parameters as soon as we get a new instance going. Since excluding both of those parameters actually causes the system to break, it would make sense to disallow that.

**Comment by paynejd** [comment]
@MisterNando I understood that the automatically created source version was the equivalent of GitHub's head. In other words, I thought that it always pointed to the current state of the source. If that is true, then it doesn't really make sense to set the "previous" or "parent" version to this. Basically, I have a lot of questions about how source versions have been implemented.

To make this concrete, let's look at the RainMED source in production (/orgs/MySDO/sources/RainMED/). Listing versions for this source results in the following:
```
GET http://api.openconceptlab.org/orgs/MySDO/sources/RainMED/versions/
```
```json
{
    "id": "554a27f9525c317489826dbf",
    "released": true,
    "owner": "MySDO",
    "owner_type": "Organization",
    "owner_url": "/orgs/MySDO/",
    "version_url": "/orgs/MySDO/sources/RainMED/554a27f9525c317489826dbf/",
    "url": "/orgs/MySDO/sources/RainMED/"
}
```

Now, let's say that over time I'm going to make lots of edits to RainMED and will produce the following version structure (starting with the automatically created source version shown above). I have made my best guess as to the correct settings for "previous" and "parent", although this doesn't entirely make sense to me given my misunderstanding of the "auto" version. See my questions below.

| version id | previous | parent | notes |
|---|---|---|---|
| _554a27f9525c317489826dbf_ | | | auto |
| v0.9 | _554a27f9525c317489826dbf_ | | |
| v1.0 | v0.9 | | |
| v1.1 | | v1.0 | |
| v1.1.1 | | v1.1 | |
| v1.2 | v1.1 | v1.0 | |
| v1.3 | v1.2 | v1.0 | |
| v2.0 | v1.0 | | |


## Questions for @MisterNando 

* Can you please verify that I am using the "previous" and "parent" fields correctly in the table above?
* Since I will be making edits to the concepts and mappings within the source, can you clarify what the "automatically generated source" is pointing to at different stages during this process? Is it the "latest" or is it different?
* What actual benefit are the "previous" and "parent" fields actually providing in terms of the API using/understanding the underlying data that the "created_on" timestamp of the version doesn't provide? Said another way, "previous" and "parent" does provide useful info to a client in visualizing a version history and hierarchy, but it is not clear to that they actually do anything in terms of defining a version for the API since that is really entirely defined by the state of the source's content at the "created_on" timestamp for the version. Can you please clarify?
* Why are concepts entirely crapping out when "previous" and "parent" are empty?
* What happens if I did something funky, like said v2.0 above had a parent of v1.1.1 and a previous of v1.0, which is logically not possible?

**Comment by MisterNando** [comment]
# Your proposed version "history" looks reasonable.
# The only time a source version is "automatically created" is when the source is initially created.  There's nothing special about this version except that it wasn't created explicitly.
# I'm not sure what value the ```created_on``` field provides other than to indicate when this version diverged from an existing version.  ```previous``` or ```parent``` will indicate to the user which version this one diverged _from_.
# Concepts are "crapping out" because you're shadowing them with a new (empty) source version.  You're saying "I want to release a new version of this source with no concepts in it".  And that's what you get!  You should be able to "recover" the shadowed concepts by re-releasing the version that contains them.
# You can create any sort of cycle you like _except_ for a self-cycle.  Basically the logic is this:
## Is there a previous_version?
### Is it myself?  Invalid!
### No? Seed the new version with the concepts from the previous one.
## Is there a parent_version?
### Is it myself?  Invalid!
### No?  Did I seed concepts yet?  If not, seed them from the parent version.

**Comment by paynejd** [comment]
@MisterNando Source versions crapped out again. I attempted to create a new source version on staging with the refreshed CIEL source with a valid `previous_version` and concepts again failed to work. Here's what I did:

* PK reloaded CIEL on staging with ~2000 concepts which automatically created the following source version for CIEL: `http://api.staging.openconceptlab.com/orgs/CIEL/sources/CIEL/5556a60150d61b4f34ceaba7/`
* I verified that all concept queries worked correctly
* I created a new source version using the following:
```
POST http://api.staging.openconceptlab.com/orgs/CIEL/sources/CIEL/versions/
```
```json
{
    "id": "0.9",
    "released": "true",
    "description": "beta",
    "previous_version": "5556a60150d61b4f34ceaba7"
}
```
* I verified that the previous version of the source version was set correctly:
```
GET http://api.staging.openconceptlab.com/orgs/CIEL/sources/CIEL/0.9/
```
```json
{
"type": "Source Version", 
"id": "0.9",
"description": "beta", 
"released": true, 
"owner": "CIEL", 
"owner_type": "Organization", 
"owner_url": "/orgs/CIEL/", 
"created_on": "2015-05-17T07:15:29.787", 
"updated_on": "2015-05-17T07:15:29.787", 
"extras": null, 
"external_id": null, 
"version_url": "/orgs/CIEL/sources/CIEL/0.9/", 
"sourceUrl": "/orgs/CIEL/sources/CIEL/", 
"previousVersionUrl": "/orgs/CIEL/sources/CIEL/5556a60150d61b4f34ceaba7/", 
"parentVersionUrl": null
}
```
* I tested retrieving concepts from the following endpoints and both returned zero concepts:
```
GET http://api.staging.openconceptlab.com/orgs/CIEL/sources/CIEL/0.9/concepts/
GET http://api.staging.openconceptlab.com/orgs/CIEL/sources/CIEL/concepts/
```
* I then tried querying concepts from the following endpoints which both worked as expected:
```
GET http://api.staging.openconceptlab.com/concepts/
GET http://api.staging.openconceptlab.com/orgs/CIEL/sources/CIEL/5556a60150d61b4f34ceaba7/concepts/
```

**Comment by paynejd** [comment]
On dev, I tried using the field `previous_version_mnemonic` instead of `previous_version`, but this also failed.

First submitted this API request:

```
POST http://api.dev.openconceptlab.com/orgs/CIEL/sources/CIEL/versions/
```
```json
{
    "id": "0.9",
    "released": "true",
    "description": "beta",
    "previous_version_mnemonic": "55572f688a86f24b48d935be"
}
```

Then tried to retrieve concepts using the following requests but both failed:
```
GET http://api.dev.openconceptlab.com/orgs/CIEL/sources/CIEL/0.9/concepts/
GET http://api.dev.openconceptlab.com/orgs/CIEL/sources/CIEL/concepts/
```

Can confirm that the source version was created here:
```
GET http://api.dev.openconceptlab.com/orgs/CIEL/sources/CIEL/versions/
```

**Comment by paynejd** [comment]
@MisterNando 

Update on staging: tried "re-releasing" the automatically generated source on staging and unfortunately same results.

Update on dev: Not sure if you already started troubleshooting dev? The automatically generated source version was renamed to "0.99" and released. The results on dev are the same though -- both of these still return 0 results:
```
GET http://api.dev.openconceptlab.com/orgs/CIEL/sources/CIEL/0.9/concepts/
GET http://api.dev.openconceptlab.com/orgs/CIEL/sources/CIEL/concepts/
```
These work fine:
```
GET http://api.dev.openconceptlab.com/concepts/
GET http://api.dev.openconceptlab.com/orgs/CIEL/sources/CIEL/0.99/concepts/
```
Note however that I used the "previous_version_mnemonic" to create the version which means that 0.9 should have worked fine. Even if "re-releasing" 0.99 worked, the source versions are still not working because their needs to be a mechanism for creating and releasing new source versions.

**Comment by MisterNando** [comment]
I think I see what's happening, @paynejd - using the *_version_mnemonic attributes, the new source version inherits the concepts, but the concepts don't get updated in Solr.  One way to ensure that they do would be to iterate over all the concepts and call save(), but that doesn't strike me as being very efficient.  At the other end of the spectrum would be to update the entire index, but that feels like too heavy a hammer.  I think the best solution would be to tap into what update_index is doing, and do that selectively on the concepts that were affected.

**Comment by MisterNando** [comment]
Correction: the *_version attributes work; not the *_version_mnemonic ones.  The Solr updating problem remains, however.

**Comment by paynejd** [comment]
Hi Aaron, I understand the reason not to go with the full reindexing but I
do not understand your recommended solution or how to implement it. Can you
clarify and make the fix?

**Comment by MisterNando** [comment]
I mean look at what this Django admin command is doing:

```./manage.py rebuild_index```

And do it selectively on the concepts in the new source version.

I don't have the bandwidth to implement this right now, but I could implement the "naive" approach as a stopgap (loop over the concepts and update them individually).

**Comment by paynejd** [comment]
Okay, please do the naive solution.

Assuming that this will be quite slow to process-- Can we make trigger to
have happen in the background?

If you could also describe a bit more what would happen ideally? That would
be helpful for next phase.

**Comment by MisterNando** [comment]
I actually figured out how to do it "the right way", but it's still a potentially long-running operation (consider how long it takes to update the Solr index for many thousands of concepts).  Should this be something that happens offline?

I'll submit my code change as a pull-request.

**Comment by MisterNando** [comment]
https://github.com/OpenConceptLab/oclapi/pull/120/

**Comment by paynejd** [comment]
This is now working! BUT, only on sources with a very small amount of concepts/mappings. I tested out on dev with the RainMED source by creating several new source versions as I created new concepts and all works correctly. However, creating new source versions failed on source with a larger number of concepts because the processing time required to process all of the concepts/mappings in the new source version is too long and results in a 404. This failed on the CIEL test dataset which contains ~2k concepts and ~5k mappings. It will be necessary to switch the creation of new source versions to a background process.

@MisterNando Can you package up the processing code into a script in the same way that you did for the background export process? The POST should still create and return the details of the new source version. However, the actual processing of the concepts/mappings should be done in the background.

@pkshiu Can you implement the script that Aaron creates?

**Comment by MisterNando** [comment]
I moved the code to a background task (see pull request), but have you thought about what the UX is going to be for this feature?  We could simply call it in place of the function I commented out, but that could be confusing to the end user.  They won't be able to see the concepts for an indeterminate amount of time... and then they will.

**Comment by pkshiu** [comment]
@paynejd so what should we do here?

**Comment by pkshiu** [comment]
@paynejd there is no additional work needed once we merge Aaron's code back. It will do the work in the background. The big question is how will the user know the the generation is complete? I cannot think of any UI that is easy to implement.

**Comment by paynejd** [comment]
@MisterNando @pkshiu Can the code set an attribute in the source version to
true while it is being processed so that the UI can react to it? e.g.
`_ocl_processing = true`

Then the UI can visually indicate that the concepts/mappings for the source
version are not yet available.

**Comment by MisterNando** [comment]
Tested my batching change locally.  Please deploy and retry.
