### ISSUE TITLE
Export dates invalid and lastUpdated timestamp must be based on the contents of the export not on current date/time

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/oclapi#122]
Export files have two big bugs. 

1. Dates are outputed into the export file incorrectly. They should be in the same format as the typical JSON output.
```
"created_on": {"$date": 1432096816796}, 
"updated_on": {"$date": 1432096816796}
```
2. The `lastUpdated` timestamp in the export filename is actually just the timestamp of when the export file is created -- this must be set to the `lastUpdated` timestamp of the contents of the export -- in other words, the most recent "updated_on" of the concepts/mappings contained in the export. Export files can be created at any time, so basing the timestamp on when the file is created is not useful and also makes synchronizing between the export file and the current state of the source impossible.

```
Filename: RainMED_0.9.20150520055640.tar
```
```json
{
  "type": "Source",
  "uuid": "555c48708a86f242b9a81e80",
  "id": "RainMED",
  "short_code": "RainMED",
  "name": "RainMED",
  "full_name": "Rain Medical Terms",
  "description": "",
  "source_type": "Dictionary",
  "public_access": "View",
  "default_locale": "en",
  "supported_locales": [
    "en"
  ],
  "website": "http:\/\/www.rainmed.org\/",
  "url": "\/orgs\/RainMED\/sources\/RainMED\/",
  "versions_url": "\/orgs\/RainMED\/sources\/RainMED\/versions\/",
  "concepts_url": "\/orgs\/RainMED\/sources\/RainMED\/concepts\/",
  "active_concepts": 4,
  "owner": "RainMED",
  "owner_type": "Organization",
  "owner_url": "\/orgs\/RainMED\/",
  "versions": 3,
  "created_on": {
    "$date": 1432096816796
  },
  "updated_on": {
    "$date": 1432096816796
  },
  "created_by": "RainMED",
  "updated_by": "paynejd",
  "extras": null,
  "external_id": "",
  "concepts": [
    {
      "type": "Concept",
      "uuid": "555c48a58a86f242b9a81e83",
      "id": "92a",
      "external_id": null,
      "concept_class": "Test",
      "datatype": "Boolean",
      "display_name": "Juice Box",
      "display_locale": "en",
      "names": [
        {
          "uuid": "e125d965156846aeba2eb2a03867aa17",
          "external_id": null,
          "name": "Juice Box",
          "locale": "en",
          "locale_preferred": false,
          "name_type": "FULLY_SPECIFIED",
          "type": "ConceptName"
        }
      ],
      "descriptions": [
      ],
      "retired": false,
      "source": "RainMED",
      "source_url": "\/orgs\/RainMED\/sources\/RainMED\/",
      "owner": "RainMED",
      "owner_type": "Organization",
      "owner_url": "\/orgs\/RainMED\/",
      "version": "555c48a58a86f242b9a81e83",
      "created_on": {
        "$date": 1432096869869
      },
      "updated_on": {
        "$date": 1432096870449
      },
      "version_created_on": {
        "$date": 1432096869869
      },
      "version_created_by": "paynejd",
      "extras": null,
      "mappings": [
      ],
      "version_url": "\/orgs\/RainMED\/sources\/RainMED\/concepts\/92a\/555c48a58a86f242b9a81e83\/",
      "url": "\/orgs\/RainMED\/sources\/RainMED\/concepts\/92a\/"
    },
    {
      "type": "Concept",
      "uuid": "555c4ad48a86f242b9a81e86",
      "id": "93b",
      "external_id": null,
      "concept_class": "Anatomy",
      "datatype": "Numeric",
      "display_name": "Juice Quantity",
      "display_locale": "en",
      "names": [
        {
          "uuid": "812657883dec4e13899ffd34f17fbeaf",
          "external_id": null,
          "name": "Juice Quantity",
          "locale": "en",
          "locale_preferred": false,
          "name_type": "FULLY_SPECIFIED",
          "type": "ConceptName"
        }
      ],
      "descriptions": [
      ],
      "retired": false,
      "source": "RainMED",
      "source_url": "\/orgs\/RainMED\/sources\/RainMED\/",
      "owner": "RainMED",
      "owner_type": "Organization",
      "owner_url": "\/orgs\/RainMED\/",
      "version": "555c4ad48a86f242b9a81e86",
      "created_on": {
        "$date": 1432097428738
      },
      "updated_on": {
        "$date": 1432097429552
      },
      "version_created_on": {
        "$date": 1432097428738
      },
      "version_created_by": "paynejd",
      "extras": null,
      "mappings": [
      ],
      "version_url": "\/orgs\/RainMED\/sources\/RainMED\/concepts\/93b\/555c4ad48a86f242b9a81e86\/",
      "url": "\/orgs\/RainMED\/sources\/RainMED\/concepts\/93b\/"
    },
    {
      "type": "Concept",
      "uuid": "555c57fe8a86f2598286a90b",
      "id": "94c",
      "external_id": null,
      "concept_class": "LabSet",
      "datatype": "Text",
      "display_name": "Juice Flavors",
      "display_locale": "en",
      "names": [
        {
          "uuid": "3ddd88ad2bdc487a997333262c95a05e",
          "external_id": null,
          "name": "Juice Flavors",
          "locale": "en",
          "locale_preferred": false,
          "name_type": "FULLY_SPECIFIED",
          "type": "ConceptName"
        }
      ],
      "descriptions": [
      ],
      "retired": false,
      "source": "RainMED",
      "source_url": "\/orgs\/RainMED\/sources\/RainMED\/",
      "owner": "RainMED",
      "owner_type": "Organization",
      "owner_url": "\/orgs\/RainMED\/",
      "version": "555c57fe8a86f2598286a90b",
      "created_on": {
        "$date": 1432100798699
      },
      "updated_on": {
        "$date": 1432100799321
      },
      "version_created_on": {
        "$date": 1432100798699
      },
      "version_created_by": "paynejd",
      "extras": null,
      "mappings": [
      ],
      "version_url": "\/orgs\/RainMED\/sources\/RainMED\/concepts\/94c\/555c57fe8a86f2598286a90b\/",
      "url": "\/orgs\/RainMED\/sources\/RainMED\/concepts\/94c\/"
    }
  ],
  "mappings": [ 
  ]
}
```

**Comment by MisterNando** [comment]
I fixed part 1 (date formats); I think the other part is for @pkshiu.

**Comment by paynejd** [comment]
Great news regarding the fix to the dates.

@MisterNando @pkshiu Regarding the lastUpdated timestamp in the filename, still need to provide the lastUpdated date to the script that creates and names the export file, and it does not make sense to re-process the contents of the export file again in order to determine the date. Aaron, can you determine the correct lastUpdated timestamp in the script that actually processes the contents of the export and hand the value over to the script that saves the file?

**Comment by MisterNando** [comment]
Wait, the last_updated date is already embedded in the S3 key.  Should be:

[owner_name]/[source_mnemonic]_[version_mnemonic].[last_updated].tgz

**Comment by paynejd** [comment]
No, that was the problem. The S3 key is the timestamp of when the file was
created and it is supposed to be the last updated. Unless I'm looking at
the wrong thing?

**Comment by paynejd** [comment]
Look at the example I gave I'm the ticket. The filename did not match the
moat recent last updated timestamp of the concepts/mappings in the export.

**Comment by MisterNando** [comment]
Well, the timestamp on the file is the value of the updated_at attribute on the source version being exported, which - if I recall correctly - gets updated whenever one of its concepts or mappings is updated OR an update is performed on the source version itself.  Is it possible we're looking at the latter case, here?

**Comment by paynejd** [comment]
I just confirmed that the "updated_on" of the source_version does NOT match the most recent "updated_on" of the concepts/mappings stored in the source version. You can verify here:

http://api.dev.openconceptlab.com/orgs/RainMED/sources/RainMED/0.9/concepts/?verbose=true
http://api.dev.openconceptlab.com/orgs/RainMED/sources/RainMED/0.9/

Aaron, can you take a look at this today? We're so close!

**Comment by MisterNando** [comment]
Right - see last comment.  Updates on concepts/mappings are only part of what triggers the "updated_on" timestamp on a source version to update.  The source version also has its own attributes, which, when updated, will trigger the updated_on timestamp to update as well.

**Comment by paynejd** [comment]
That's fine if that's the way that the updated_on field of the source version is maintained, but that is not acceptable for exports. Exports must be accompanied with a value of the most recent updated_on of the concept/mappings that it contains.

**Comment by paynejd** [comment]
@pkshiu Set the filename saved to AWS to include the lastUpdated value that Aaron's script provides.

@MisterNando Please provide details of your implementation so that PK can do this.

**Comment by pkshiu** [comment]
Hey @paynejd , the export pathname is set during the export creation process. I don't have to do anything. Currently as Aaron said, it is set in the model:

https://github.com/OpenConceptLab/oclapi/blob/master/django-nonrel/ocl/sources/models.py#L87

@MisterNando you can just change this to whatever is the right value, no?

**Comment by MisterNando** [comment]
Yes - that's what I did.
