### ISSUE TITLE
limit=0 causes zero (instead of unlimited) concepts/mappings results for source endpoint when including concepts/mappings

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/oclapi#123]
The addition of `limit=0` as a URL parameter in following GET request should return ALL results (same as other endpoints). Instead, it returns zero results.
```
GET http://api.dev.openconceptlab.com/orgs/RainMED/sources/RainMED/?updatedSince=2015-05-20T05:46:40Z&includeConcepts=true&includeMappings=true&includeRetired=true&limit=0
```

**Comment by MisterNando** [comment]
Actually, there was a hard cap implemented (100), but not for this particular query.  I enforced the hard cap on this query as well.
