### ISSUE TITLE
Requesting mappings at the source level results in 404

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/oclapi#127]
Requesting top-level mappings (e.g. `GET /mappings/`) works as correctly. However, after lots of mappings are loaded into the system, requesting mappings at the source level (e.g. `GET /orgs/CIEL/sources/CIEL/mappings`) results in a 404. This request fails even if limit is set to something small (e.g. `limit=10`). Note that the request works as expected on staging and dev as there are <5k mappings, but it fails on production. Fortunately, `GET /orgs/CIEL/sources/CIEL/?includeMappings=true&includeConcepts=true` still works correctly.

Emailing with Aaron, it looks like there are 2 issues here:

**Issue 1:** 
The general search strategy is:
- Apply the filters that are represented in Mongo (e.g. permissions)
- Apply the filters that are represented in Solr (any fields defined in **/search_indexes.py)
- Calculate the intersection

Step 3 can be quite expensive; in this case, it's causing the timeout.  But, in this case, I'm also not sure that it's necessary.  I think these 2 filters are doing the exact same thing:

https://github.com/OpenConceptLab/oclapi/blob/master/django-nonrel/ocl/mappings/views.py#L137
https://github.com/OpenConceptLab/oclapi/blob/master/django-nonrel/ocl/mappings/filters.py#L18

Try it without the first one, and see if you get the desired result.

**Issue 2:**
MappingListView extends ListWithHeadersMixin, which is the thing that adds the headers, but it also overrides the list() method... which is the thing that adds the headers.  Play around with it and see if there's a way to get the desired object_list without overriding the entire list() method.

**Comment by MisterNando** [comment]
Checked in a fix, but still needs to be tested in prod.

**Comment by paynejd** [comment]
Works in dev. Will promote to prod and test after all the other tickets have been tested.
