### ISSUE TITLE
/orgs/:org/sources/:source/ extras are different than /orgs/:org/sources/:source/extras/

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/oclapi#133]
Somehow there are two separate dictionaries of extras for sources. There should obviously only be one. Compare the extras in following:

GET http://api.dev.openconceptlab.com/orgs/CIEL/sources/CIEL/
GET http://api.dev.openconceptlab.com/orgs/CIEL/sources/CIEL/extras/
GET http://api.dev.openconceptlab.com/orgs/CIEL/sources/CIEL/extras/about/

**Comment by MisterNando** [comment]
Source versions were not inheriting extras from their corresponding sources.  This will not be an issue going forward, but left alone, existing source versions will remain "out of sync".

**Comment by paynejd** [comment]
Can you please clarify -- this means that all the existing source versions
still have the old behavior? Or that they are fixed, but that the data may
not reflect whatever was added into the "other extras"?

**Comment by MisterNando** [comment]
Yes, the fix would only apply to source versions that are created after deploying this code change.  (Although a data fix would be fairly straightforward to implement on the Django command line, if necessary.)

**Comment by paynejd** [comment]
Could you go ahead and create the script that fixes existing sources?
Re-doing production would take ~72 hours, so a command-line script is the
way to go. Thanks!

**Comment by MisterNando** [comment]
Sent script in an email; copying here:

```
(ocl_api)$ ./manage.py shell
>>> from sources.models import SourceVersion
>>> for sv in SourceVersion.objects.filter(extras__isnull=True):
...     sv.extras = sv.versioned_object.extras
...     sv.save()
...
>>>
```
