### ISSUE TITLE
Zero retired concepts are actually retired upon import

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/oclapi#135]
When running the import scripts, retired concepts are not retired. We ended up having to write a separate script that runs after the import script has completed that simply calls the API to retire any concepts that should have been retired. Unfortunately, this behavior will only work on the initial import of a dictionary and not when "re-importing" a dictionary over itself to update it.

Aaron indicated that there is code in the import script specifically dedicated to retired concepts (see https://github.com/OpenConceptLab/oclapi/blob/master/django-nonrel/ocl/oclapi/management/commands/import_concepts_to_source.py#L105). In the current implementation, the "retired" attribute is handled independently of the other attributes.

However, the above code is either not executed or does not run correctly, because when the import script is done running (for example, on the full CIEL dictionary or on the test CIEL dictionary), zero concepts are retired.

**Comment by MisterNando** [comment]
FYI - this was very slow to test, due to the index update, so I made a small change that will enable us to run partial updates (e.g. using update_index with the --age, --start & --end flags).

**Comment by paynejd** [comment]
Can you please provide quick instructions how to use the --age, --start,
--end flags to that I can also test on dev & staging?

**Comment by MisterNando** [comment]
Sure - there's some good documentation here:

http://django-haystack.readthedocs.org/en/latest/management_commands.html#update-index
