### ISSUE TITLE
.com and .org do not all work to access the API and they're different on each environment

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/oclapi#136]
Here are the test results on each environment:
* Development - only .com works
* Staging - only .com works
* Production - only .org works

**Comment by pkshiu** [comment]
What combination should we allow? The issue I think it's in the nginx setup because we "allow in" specific domains.

**Comment by paynejd** [comment]
Let's force all API work to be done on .com. .org should be blocked for the API.

For the website, instead of supporting two domain names, can we just set it up so that all .orgs redirect to the .com?

**Comment by paynejd** [comment]
For the API, let's only support .com. .org should be blocked.

For the website, rather than support multiple domains, can we just automatically redirect all the .orgs to .com?

**Comment by pkshiu** [comment]
Currently production is .org, staging and dev is com. This is mapped in the nginx/sites-available/ocl file ,but those files are AUTO-GENERATED by fabric. See wiki documentation.

**Comment by paynejd** [comment]
.org has been disabled for the website and the API and everything has been switched to .com.
