### ISSUE TITLE
Sources owned by orgs have updated_by & created_by set to org ID instead of username

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/oclapi#138]
When creating a source that is owned by an organization, the `created_by` and `updated_by` fields are set to the organization ID instead of the user that created/updated it. Actions can only be performed by users, so this is invalid.

Is this being done as a way to propagate permissions?

![image](https://cloud.githubusercontent.com/assets/1189689/8682862/4023fba2-2a3d-11e5-9ff3-2c2bab0508b0.png)

**Comment by AnjaliWadhwa** [comment]
This is fixed and working fine now.
