### ISSUE TITLE
Facets are incorrect for org sources results

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/oclapi#139]
/orgs/CIEL/ owns 2 sources (see `GET /orgs/CIEL/sources/`)

The results are correct, but when includeFacets is set to true, the returned facets seem to reference all or most of the sources. It appears that a different set of criteria were applied to the search results as were applied to the facets.

**Comment by MisterNando** [comment]
Recall the strategy described in #127:

**Comment by paynejd** [comment]
Can you please describe with as much detail as possible here which/how filters are applied in Mongo vs. Solr?

My testing shows that this now works correctly!

**Comment by MisterNando** [comment]
Well, the details vary across the different endpoints, but the path through the call stack typically looks like this:

1. "List" view implements ```get``` (or extends ListAPIView, which implements ```get```) which responds to ```GET``` requests.
2. ```get``` calls ```list``` (which is often inherited from ```ListWithHeadersMixin```, which supplies the headers).
3. ```list``` calls ```filter_queryset``` on the result of ```get_queryset```.
4. ```get_queryset``` applies filters against the Mongo collection.  Most often, this method is inherited from (or extends) one of the base class implementations defined here: https://github.com/OpenConceptLab/oclapi/blob/master/django-nonrel/ocl/oclapi/views.py
5. ```filter_queryset``` applies filters against the Solr index.  Again, its implementation varies across endpoints.  (Each view specifies a ```filter_backends``` array, which is essentially a search path over classes that implement ```filter_queryset```.)  Some of the filter backends will calculate the intersection between the Mongo Queryset and the Solr SearchQueryset (children of ```HaystackSearchFilter```), and others (children of ```SimpleHaystackSearchFilter```) will simply return the SearchQueryset (when the intersect operation is redundant).

**Comment by paynejd** [comment]
Thanks for the additional info -- very helpful.
