### ISSUE TITLE
GET request of many Concept Versions returns {"detail":"Not found"}

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/oclapi#147]
In all 3 server environments and with all concepts tested, requesting concept versions often fails with an API response of {"detail":"Not found"} even though the concept version exists.

For example, take a look here on the Web app: http://www.openconceptlab.com/orgs/CIEL/sources/CIEL/concepts/32/history/

Or the same thing through the API:
GET http://api.openconceptlab.com/orgs/CIEL/sources/CIEL/concepts/32/versions/

![image](https://cloud.githubusercontent.com/assets/1189689/9369682/d6e4c2e8-4698-11e5-9d83-a01a2526b607.png)

However, a GET request only works on one of the concept versions --- take a look at both of the following -- the first one fails but the second one works as expected:
* GET http://api.openconceptlab.com/orgs/CIEL/sources/CIEL/concepts/32/5580979f525c312dca1103f7/
* GET http://api.openconceptlab.com/orgs/CIEL/sources/CIEL/concepts/32/55c12dca525c313e877dc8b3/

And another discordant pair:
* GET http://api.openconceptlab.com/orgs/CIEL/sources/CIEL/concepts/36/55c12e0b525c313e877dc8b7/
* GET http://api.openconceptlab.com/orgs/CIEL/sources/CIEL/concepts/36/5580979f525c312dca1103ff/

**Comment by MisterNando** [comment]
@paynejd - just pushed a change that should fix this.  (Verified locally against data in dev.)  Please deploy and retry.

**Comment by paynejd** [comment]
This checked out on dev! Will promote to staging/production later this week to confirm and then close the ticket.

**Comment by paynejd** [comment]
The update fixed one problem but created a new one: GET requests only work on explicit source versions but fail when requesting the only the concept.

This fails:
* GET http://api.dev.openconceptlab.com/orgs/CIEL/sources/CIEL/concepts/4/

But these all work:
* GET http://api.dev.openconceptlab.com/orgs/CIEL/sources/CIEL/concepts/4/versions/
* GET http://api.dev.openconceptlab.com/orgs/CIEL/sources/CIEL/concepts/4/558821c68a86f249005cade0/
* GET http://api.dev.openconceptlab.com/orgs/CIEL/sources/CIEL/concepts/4/55e891338a86f25405ca7429/

**Comment by MisterNando** [comment]
Yeah, that's a funny query, because it's a concept URL, but it renders a concept version object.  I had to add a special case for it.

**Comment by paynejd** [comment]
This has been fixed.
