### ISSUE TITLE
Multiple requests to source version export while processing should not create multiple export files

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/oclapi#153]
If an export file does not exist, then OCL initiates a task to generate the export file and saves it on AWS S3 when done. In the meantime, it returns a 204 to the requester to let them know that it is being processed.

However, each additional GET request while the export is being processed causes a new export task to start. With just a few of these requests, it quickly eats up server resources and sometimes processes start getting killed.

Take a look at this for examples:
http://docs.celeryproject.org/en/latest/tutorials/task-cookbook.html#ensuring-a-task-is-only-executed-one-at-a-time

**Comment by paynejd** [comment]
This appears to be working correctly, but I need instructions from Thought Works on how to access flower on each environment in order to confirm.

**Comment by snyaggarwal** [comment]
Flower is running on port 5555 on each environment.
It will list down the task performed, status and other details.
