### ISSUE TITLE
Reduce concept import time to 5 seconds or less each

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/oclapi#155]
Adding/updating concepts is slow. It took between 30-60seconds per concept before I started optimizing. I switched to a dedicated server and made a number of code and index improvements which got the time down to ~11 seconds per concept. This is a huge improvement, however, the imports are increasingly slow as the size of the database increases, so it is critical that this time is decreased much further. Current target is sub-5-seconds. The proposed **sequential source version model** should result in huge improvements (closer to 1sec), but that won't be done anytime soon. Below are the lower hanging fruits-- a few key bottlenecks that could be addressed prior to the full re-architecting.

Concept lookups are indexed and are very fast. Concept version lookups could be fast, but the current setup makes them slow if the lookup includes a check on its membership in a particular source version. Updating the array of concept versions linked to a source version and updating a specific concept version are also slow and could be sped up a lot.

1. The `id__in=self.source_version.concepts` expression in `handle_concept` causes a very inefficient and long-running query for every single concept that exists, whether nodiff or an update. Code here: https://github.com/OpenConceptLab/oclapi/blob/master/django-nonrel/ocl/oclapi/management/commands/import_concepts_to_source.py#L155-L156

This issue will be resolved if the **sequential source version model** is implemented. Until then, it may be possible to change the query to compare the conceptversion ObjectID directly to the sources_sourceversion.concepts array, which runs in ~20ms instead of 200-400ms. Here's an example:

```
# This finds source versions of a specific source that contain the specified concept version
db.sources_sourceversion.find( { versioned_object_id: '55804807525c311e7eb3858f', concepts: '560169b6525c3109d57b1e0f' }, { concepts: { $slice: 1 }, mappings: 0, extras: 0 } )
```

2. The next (super) long-running query occurs when the new conceptversion ID is added to the sourceversion concepts array. It is possible to use the $pull operator to remove the old conceptversion ID and the $push operator to add the new conceptversion ID. This needs to be tested, but it should be significantly faster than updating the entire array in code and then saving the update to mongodb afterwards.

3. The third long-running query, although this is not nearly as long as the 2 above, is the concept version update itself. It may be possible to speed this up a lot with some index work.

4. Generally, additional index work in MongoDB could probably yield some significant improvements.

5. It appears that Solr is updating records in real-time, at least on production. This is not the intended behavior, but I can't seem to figure out how to turn realtime signal processing off in Haystack, despite having hacked around with settings.py and the importer's __init__.py module.
* UPDATE -- Solr was not updating records in real-time. I was looking at the concept details pages which bypasses Solr and goes straight to MongoDB, so it is always up-to-date. The indexes (search pages) were still out-of-date, so this issue is solved. It may actually be worth looking at turning this on, as it might be possible for this to happen in real-time without a big slowdown.

6. Initial import of CIEL dictionary takes ~50 hours. I expect that most of the import time is taken up checking on the indexes. It may be possible to disable checks on these indexes (via a command-line flag) during the import of a *trusted* source. Profiling should reveal if this would yield significant improvements.

**Comment by bhawnasingla** [comment]
Tasks:
181. Unicode Fix
182. Map Concept IDs for Source version
183. Cache source ids in mapping import job
184. Introduce switch for inline indexing
185. Batch processing of records
186. Mongo bulk import
187. Model change of sourceversion/conceptversion
