### ISSUE TITLE
Add ability to maintain version history for mappings (same as for concepts)

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/oclapi#157]
- Mapping page should have a 'History' tab next to 'Details'. 
- Any modification in mapping should create a new version of mapping internally which should be visible under 'History' tab.
- Each version of mapping should have a unique id.
- User should be able to view details of any of the previous version(s) of mapping by clicking on the search icon against each version under history tab.

Mapping version is same as for concepts. Adding sample screenshot of concept page below for reference.

<img width="1274" alt="screen shot 2016-08-31 at 21 59 29" src="https://cloud.githubusercontent.com/assets/3176602/18137592/92bd39c6-6fc6-11e6-84de-36ed2239ee35.png">

**Comment by AnjaliWadhwa** [comment]
"#145 - Similar to source.active_concepts, active_mappings should stay up to date as the number of active mappings in a source is modified" should also be implemented in this card.

**Comment by AnjaliWadhwa** [comment]
We need to add 'Update Comment' field same as concepts to track reason for update while editing the Mapping. I have created a separated tech task for it.

**Comment by paynejd** [comment]
Jon's feedback:
- Still need to add `Update Comment` field
- When viewing a mapping version, still show the tabs so that the user can easily navigate back to the Mapping History -- right now no tabs are shown when viewing a mapping version

**Comment by AnjaliWadhwa** [comment]
Feedback has been fixed and working fine.
