### ISSUE TITLE
Export metadata should contain values from the source version not the source

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/oclapi#163]
Source exports include the source version details as well as all the concepts and mappings contained in the source version (based on the flags specified in the export request). However, the fields in the export are always set to whatever the values of the source version attributes are at the time that the export file is created, rather than the details of the specific source version being requested. This means that the export file may look slightly different each time the export is created if the concepts, mappings or source metadata have changed. The correct behavior is that the export file includes the metadata from the specific source version (i.e. number of mappings, concepts, and other source metadata) which should not change.

Note that for this to work, a source version should "save" the values of the source into the source version at the time it is created. For example, it will probably look something like this:

```
{
  u'type': u'Source Version',
  u'id': u'v2015-08-24',
  u'owner': u'CIEL',
  u'owner_type': u'Organization',
  u'owner_url': u'/orgs/CIEL/',
  u'parentVersionUrl': None,
  u'previousVersionUrl': u'/orgs/CIEL/sources/CIEL/v2015-05-14/',
  u'sourceUrl': u'/orgs/CIEL/sources/CIEL/',
  u'updated_on': u'2015-12-02T18:16:22.099',
  u'version_url': u'/orgs/CIEL/sources/CIEL/v2015-08-24/'
  u'created_on': u'2015-09-18T16:33:13.382',
  u'description': u'Updating to CIEL release date 2015-08-24',
  u'external_id': None,
  u'extras': None,
  u'released': True,
  u'source':{
    u'type': u'Source',
    u'id': u'CIEL',
    u'name': u'CIEL',
    u'owner': u'CIEL',
    u'owner_type': u'Organization',
    u'owner_url': u'/orgs/CIEL/',
    u'active_concepts': 51073,
    u'concepts_url': u'/orgs/CIEL/sources/CIEL/concepts/',
    u'created_by': u'CIEL',
    u'created_on': u'2015-06-16T12:00:07.082',
    u'default_locale': u'en',
    u'description': u'Columbia International eHealth Laboratory concept ID',
    u'external_id': u'249b13c8-72fa-4b96-8d3d-b200efed985e',
    u'full_name': u'Columbia International eHealth Laboratory',
    u'public_access': u'View',
    u'short_code': u'CIEL',
    u'source_type': u'Interface Terminology',
    u'supported_locales': [u'en'],
    u'updated_by': u'sysadmin',
    u'updated_on': u'2015-08-10T10:39:11.758',
    u'url': u'/orgs/CIEL/sources/CIEL/',
    u'uuid': u'55804807525c311e7eb3858f',
    u'versions': 5,
    u'versions_url': u'/orgs/CIEL/sources/CIEL/versions/',
    u'website': u''
  }
}
```

**Comment by AnjaliWadhwa** [comment]
Export is not working as expected in this story.
Also need to implement this for Collection versions

**Comment by AnjaliWadhwa** [comment]
Feedback:
* Mappings are not coming up in export for source and collection version.
