### ISSUE TITLE
Implement retire and delete operations on collection versions

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/oclapi#170]
Note that source version deletes may have already been implemented at the API level, but definitely not implemented in the user interface -- this should be tested.

Retiring of a source/collection version should clearly mark the version as not intended for use.

**Comment by amitendc** [comment]
**Deletion of Source/Collection :-** 
- Delete will mark the source version as 'not active'.
- Delete will work on only the latest version (not on previous versions)
- The version of source to be deleted should not have 'Released' tag associated.
- The deleted source and associated concepts/mappings cease to appear on UI (not indexed)

**Retire of Collection/Source :- **
- ?

**Comment by AnjaliWadhwa** [comment]
UI design:
* If the resource (Source/ Collection version) is retired, it should not be allowed to release.
* Also if already released version is being retired then show only retired flag.

<img width="1024" alt="2016-09-13" src="https://cloud.githubusercontent.com/assets/3176602/18555812/d701c6ee-7b86-11e6-9260-58a7910310f1.png">

**Comment by AnjaliWadhwa** [comment]
Permissions will be implemented in #207

**Comment by paynejd** [comment]
Retiring and deletion of collection versions is working correctly.

Note that as discussed, none of the collection's concepts/mappings/references are crossed out even if part of a retired collection version -- this is the correct behavior, and I am noting that here because the above comment states that references will be crossed out.
