### ISSUE TITLE
Showcase/QA env setup

### ISSUE THREAD

**Issue by AnshuAg** [OpenConceptLab/oclapi#174]

**Comment by bhawnasingla** [comment]
- Setting up a new stage 'DEPLOY-QA' in both the snap-ci pipelines: oclapi and ocl_web
- settings.py contains different environment for showcase: Directory structure modified a bit to contain different file for each environment
- new docker file for showcase environment
- seed data for token by api that are shared on web

**Comment by AnjaliWadhwa** [comment]
This setup is complete
