### ISSUE TITLE
Freeze the version of Collection on creation 

### ISSUE THREAD

**Issue by amitendc** [OpenConceptLab/oclapi#175]
### Head
1. In the version tab of the collection, display ‘+ New Collection Version’ to create new version of Collection.
2. Name auto-generated version of Collection as "head"
3. In the versions tab of Collection, the default order is HEAD first and then other versions (order by updated_at)
4. All updates to collection should become part of "head"
5. HEAD version should not be released by default
6. ~~Only Head version should display “ + New Concept/Mappings/Source/Collection" button in version  Collection versions.~~
6. Only Head version should display “ + New Collection Version" link in the versions tab.
7. Display ‘Head’ as default option in the dropdown in ‘Concept/Mapping/References’ tabs of the Collection. All new updates part of the head should be displayed in the listing.

### Previous Version
1. Ensure no updates on versioned Collection or associated references of versioned Collection
2. No updated information of concepts in previous versions of Collection
3. Edit of a versioned concept shouldnt be allowed on UI

**Comment by AnjaliWadhwa** [comment]
Testing complete.

**Comment by paynejd** [comment]
Testing for this has been completed and works as expected
