### ISSUE TITLE
Cloud Deployment for Staging

### ISSUE THREAD

**Issue by amitendc** [OpenConceptLab/oclapi#177]
1. New Droplet in DO with production like configs
2. New manual stage in ocl_web/oclapi pipelines downstreams from qa/showcase.

**Comment by AnshuAg** [comment]
Having an environment on cloud to showcase and test the stories.

**Comment by snyaggarwal** [comment]
@AnshuAg -- This is not a duplicate card -- #174 talks about showcase/qa setup and this card is staging for UAT/Performance testing.

**Comment by paynejd** [comment]
Staging deployment appears to be done to me. If you can confirm this, then please close.
