### ISSUE TITLE
Generate versions of Collections

### ISSUE THREAD

**Issue by amitendc** [OpenConceptLab/oclapi#179]
https://github.com/OpenConceptLab/oclapi/wiki/collections#create-new-version-of-a-collection

## Tasks

1. Display the listing of all versions of Collections in Versions tab.
2. Click '+ New Collection Version' on the top left to open the versions.
3. Add Collection Version details and save to create new version of Collection.

Note: UI similar to Source version creation.

### Note:
Breaking Release/Un-release into a separate story as it involves UI changes.

![screen shot 2016-08-11 at 5 06 44 pm](https://cloud.githubusercontent.com/assets/18673796/17587450/207f853e-5fe6-11e6-9806-eb147131289a.png)

**Comment by AnjaliWadhwa** [comment]
Testing complete.

**Comment by paynejd** [comment]
Testing complete!
