### ISSUE TITLE
Add lastUpdated into the response header of export request

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/oclapi#191]
When a client system requests an export file, it must record the lastUpdate timestamp of the export file in order to properly filter which content it should synchronize with on subsequent requests. Right now, lastUpdated is only stored in the filename of the export, which is somewhat awkward. lastUpdated should also be included as an attribute in the response header.

**Comment by rohitggarg-tw** [comment]
Adding lastUpdated and lastUpdatedTimezone as headers, timezone would be required in order to parse the time correctly.

**Comment by paynejd** [comment]
Can you please describe here how the lastUpdated time is calculated for source and collection exports?

**Comment by snyaggarwal** [comment]
lastUpdated is getting populated by the same way we do for export filename.
-- last child update:
  * max(last_concept_update, last_mapping_update) or self.updated_at
