### ISSUE TITLE
Concept authoring

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/oclapi#192]
https://github.com/OpenConceptLab/oclapi/wiki/concepts#create-new-concept

User should be able to create a new concept. Below are the fields.
- Concept ID: #216 
  - Automatic update of the URI for the concept as you are typing
  - Live validation of whether the Concept ID is valid and unique
- Concept Class and Datatype #217 
  - Dropdowns should be populated from OCL:Classes and OCL:Datatypes
  - Dropdown must allow entry of custom values (values that are not in the dropdown)
- Name/Description Types #217 
  - Must be alphanumeric plus hyphen/underscore
  - Should be pre-populated with dropdown from OCL:NameTypes and OCL:DescriptionTypes
  - Dropdowns must support entry of custom values
  - In the future, these should support multiple comma-separated values
- Names and descriptions 
  - At least one name is required to create/update a concept
  - In the furture, UI must allow creation of multiple names/descriptions -- when editing, it is acceptable to edit only one name or description at a time (although multi-edit is ideal)
- Name/Description Locale #218 
  - Locale dropdown should be populated by OCL:Locales using the 2 letter codes (NameType=ISO-639-1)
  - Dropdown should ideally allow filtering by either the code or the full name
  - Locale dropdown should work with both names and descriptions
- External ID
  - Live validation of whether External ID is unique within the source -- maybe just warn if its not unique? Or is this a requirement?
- Extras #220 
  - Allow creation of multiple extras -- when editing, it is acceptable to edit only one extra at a time (although multi-edit is ideal)
- Mappings
  - It is not required at this time to be able to create the mappings for a concept at the time of concept creation or in the screen for editing of concepts -- this will be a separate process for now

**Comment by AnjaliWadhwa** [comment]
Note:
* Creation of multiple names, descriptions and extras will be done in a separate story in future.

**Comment by AnjaliWadhwa** [comment]
**Split into multiple stories** 
Create concept fields - #216, #217, #218 
Edit concept - #203
