### ISSUE TITLE
Setup flower to monitor celery jobs

### ISSUE THREAD

**Issue by snyaggarwal** [OpenConceptLab/oclapi#194]

**Comment by AnjaliWadhwa** [comment]
Flower UI can be accessed at port 5555, on local as well as showcase and staging.
* showcase.openconceptlab.org:5555
* staging.openconceptlab.org:5555

**Comment by paynejd** [comment]
This is complete for showcase and UAT. Will need to verify on production. Closing.

**Comment by AnjaliWadhwa** [comment]
Flower setup for production is done. It is now available at http://openconceptlab.org:5555/
