### ISSUE TITLE
Release / Un-release one or more versions of Collection and Source

### ISSUE THREAD

**Issue by amitendc** [OpenConceptLab/oclapi#196]
### Tasks:

1. On creation of a new Version of Collection, it should be released automatically.
2. User should have option to Release any of the listed version of collection.
3. User should have option to Un-release a (already released) version of collection. 

Question?
1. Should at lease one version of collection be in released state?

**Comment by paynejd** [comment]
A few corrections:

- Repository versions should never be released automatically
- A repository is not required to have any released versions -- in this
situtation, the "latest" magic keyword would need to throw an error
- User should have option to release any of the listed versions of a
repository, except head, which can never be released
- Agreed, user should have option to un-release any already released
repository version

**Comment by AnjaliWadhwa** [comment]
Updates:
* UI should be designed as shown in the image below.
* All the members of organisation should have permission to Release / Un release a version of collection.
* Any user who is not a member of organisation should not see any radio buttons to Release / Un release a version. They should only see appropriate tag against the version - RELEASED / UNRELEASED.

 
![20160830_154104](https://cloud.githubusercontent.com/assets/3176602/18135387/660f4b00-6fbf-11e6-98ff-d5fdd3e6ba94.jpg)

**Comment by AnjaliWadhwa** [comment]
'latest' keyword does not work properly when we either do not have any release versions or when we have more than one release versions. Created a separate story for it https://github.com/OpenConceptLab/ocl_web/issues/109

**Comment by paynejd** [comment]
This has been fully tested and is working according to the spec.
