### ISSUE TITLE
Staging shows wrong number of sources on search

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/oclapi#197]
The filters for staging is showing the incorrect number of sources. This is true for the global search (http://staging.openconceptlab.org/search/?type=sources) and for the organization-specific search (http://staging.openconceptlab.org/orgs/EthiopiaMOH/sources/). See image below for an example -- there is only 1 source in EthiopiaMOH but the filters show 4.

![image](https://cloud.githubusercontent.com/assets/1189689/18110587/1d41a038-6ed6-11e6-9547-c36773021038.png)

**Comment by AnjaliWadhwa** [comment]
This issue is fixed now. It was a data issue as we had some data in Solr but it was not in DB.

**Comment by paynejd** [comment]
Fixed
