### ISSUE TITLE
Global search throws Internal Server Error

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/oclapi#198]
Staging throws an error when navigating to the global search page with some combinations of parameters. For example, these all throw errors:

* http://staging.openconceptlab.org/search/?q=
* http://staging.openconceptlab.org/search/?q=&sort=Best+Match
* http://staging.openconceptlab.org/search/?type=concepts

![image](https://cloud.githubusercontent.com/assets/1189689/18110755/4162ee1c-6ed7-11e6-987e-072ac7053580.png)

**Comment by AnjaliWadhwa** [comment]
This issue is fixed now. It was a data issue as we had some data in Solr but it was not in DB.

**Comment by paynejd** [comment]
Fixed
