### ISSUE TITLE
Implement retire and delete operations on Source versions

### ISSUE THREAD

**Issue by AnjaliWadhwa** [OpenConceptLab/oclapi#201]
**Deletion of Source Versions** (MEDIUM PRIORITY)
- User goes to the versions tab and Deletes any listed version except HEAD. (removed)  
- The earlier version's 'previous_version_url' is updated to the later version. This is not implemented yet but needs to be fixed separately.
- The deleted version is not visible on the Version tab of Collection. (or any of the other drop downs)

### Note:
- parent_version_url - Deprecated
- previous_version_url - Needs to be updated if the previous version is deleted. Workaround is to track created_on field to track the version sequence.. 

**Retire of Source Versions** (LOW PRIORITY)
- User goes to the versions tab and mark any listed version as Retired. (Not intended for use).
We need to add a check box similar to Release for each version except HEAD. 
- The version is marked "retired=true" in database. (Note that we need to add a new attribute 'retired' in db).
- The Version should display strikethrough and tagged "Retired". (still visible on the drop downs). - The user can click on the version and land on Version Page of the Source.
- In Concepts & Mappings tab, all concepts and mappings under this version will be unaffected. They will not be strike through.

**Note: Retire HEAD and entire Source is not allowed**

**Comment by AnjaliWadhwa** [comment]
UI design:
* If the resource (Source/ Collection version) is retired, it should not be allowed to release.
* Also if already released version is being retired then show only retired flag.

<img width="1024" alt="2016-09-13" src="https://cloud.githubusercontent.com/assets/3176602/18555812/d701c6ee-7b86-11e6-9260-58a7910310f1.png">

**Comment by AnjaliWadhwa** [comment]
Permissions will be implemented in #207

**Comment by paynejd** [comment]
This is working great
