### ISSUE TITLE
Edit Concept

### ISSUE THREAD

**Issue by AnjaliWadhwa** [OpenConceptLab/oclapi#203]
Pre-requisites: #192 

https://github.com/OpenConceptLab/oclapi/wiki/concepts#edit-concept

User should be able to edit following fields in concept.
- Concept Class and Datatype
- Name/Description Types
- Names and descriptions
- Name/Description Locale
- External ID
- add new fields 'update_comment' - string - text describing the reason for the update;

Note:
- Edit of concept will generate a new version of the underlying concept.
- Creation/Edit of multiple names, descriptions and extras will be done in a separate story in future.

**Comment by AnjaliWadhwa** [comment]
Feedback:

* On edit, values for 'NameType' and 'DescriptionType' in dropdown is set to None and even if changed it is not being saved in db.

**Comment by paynejd** [comment]
There are a couple of small changes needed with concept editing:

1. Empty descriptions should not be saved -- currently, the blank
description with its description type and
2. Name and Description Locales should default to the source's
`default_locale` setting
3. Empty first custom attribute should not prevent form submission -- one
empty custom attribute is in the new concept form by default, and if the
user doesn't enter any data in the custom attribute, it prevents the user
from saving the concept -- instead, allow the user to submit it and throw
out the custom attribute on the back end
4. Name Type of first concept name should default to "Fully Specified" --
additional names can default to "None" or simply blank
5. Description field must allow multi-line answers -- assuming that we need
to change this to a *textarea* control?
6. First concept name and description should default to
locale_preferred=true

**Comment by AnjaliWadhwa** [comment]
Comments on above feedback:
1. It will be fixed in https://github.com/OpenConceptLab/ocl_web/issues/121
2. Points 2,5,6 - This is feedback for #218 and will be fixed in that card.
3. Created #291 for it
4. For point 5 above, created #292 for it.

**Comment by AnjaliWadhwa** [comment]
Feedback for this card is fixed and working fine.
