### ISSUE TITLE
Export of HEAD of Source / Collection should not be allowed

### ISSUE THREAD

**Issue by AnjaliWadhwa** [OpenConceptLab/oclapi#205]
Currently we are able to export HEAD of Source and Collection. It should not be allowed. User should only be allowed to export a version.

**Comment by AnjaliWadhwa** [comment]
Response code in this case should be '405 Not Allowed'

**Comment by AnjaliWadhwa** [comment]
This is now fixed and works fine for source and collection under user and org.

**Comment by paynejd** [comment]
Great, this works as expected.
