### ISSUE TITLE
Public org members list empty if not a member of organization

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/oclapi#215]
Logged in as paynejd on showcase, if I look at a public organization owned by someone else, then the members list shows up empty:

![image](https://cloud.githubusercontent.com/assets/1189689/18519178/eb6f5914-7a70-11e6-94ef-a88afd4d246d.png)

**Comment by AnjaliWadhwa** [comment]
This is fixed and working fine.

* Unauthenticated user can just view the members of org:

<img width="1280" alt="unauthenticated_member" src="https://cloud.githubusercontent.com/assets/3176602/19548914/d45746be-96be-11e6-9fd6-e85e01015617.png">

* Authenticated non-member can also just view the members of org:

<img width="1280" alt="authenticated_but_non_member" src="https://cloud.githubusercontent.com/assets/3176602/19548973/1bff0f4c-96bf-11e6-928d-d8b8753c3b9f.png">

* Owner / member of org can view/edit/delete the members:

<img width="1280" alt="owner" src="https://cloud.githubusercontent.com/assets/3176602/19548963/127acea2-96bf-11e6-99e0-64124cbd20b2.png">

<img width="1276" alt="member_of_org" src="https://cloud.githubusercontent.com/assets/3176602/19548942/f317d320-96be-11e6-9683-56999c0e0fb3.png">
