### ISSUE TITLE
Enhance 'Concept ID' field in concept creation

### ISSUE THREAD

**Issue by AnjaliWadhwa** [OpenConceptLab/oclapi#216]
https://github.com/OpenConceptLab/oclapi/wiki/concepts#create-new-concept

**Implement below enhancements for 'Concept ID'**
- Automatic update of the URI for the concept as you are typing. This is shown below the concept id text field.
  - Your new concept will live at: http://www.openconceptlab.com/[owner-type]/[owner]/sources/[source]/concepts/[concept-id]/
- Live validation of whether the Concept ID is valid and unique

**Note:**
- Concept IDs cannot be changed after a concept is created.

**Questions?**
- Will live validation possibly have performance impact?

**Comment by AnjaliWadhwa** [comment]
As discussed in the BA call today, we will not do live validation for Concept Id as it is low priority for now and has performance impact.

**Comment by AnjaliWadhwa** [comment]
URI is not being updated while we type Concept Id. Moving it back to Dev.

**Comment by paynejd** [comment]
Please remove the text "[concept-id]" from the URL entirely, even when the code is blank. Otherwise, this looks good!
