### ISSUE TITLE
Enhance Name/description types, concept class and datatype fields in concept creation

### ISSUE THREAD

**Issue by AnjaliWadhwa** [OpenConceptLab/oclapi#217]
https://github.com/OpenConceptLab/oclapi/wiki/concepts#create-new-concept

**Concept Class and Datatype**
- Dropdown should be populated from OCL:Classes and OCL:Datatypes.[ Refer this sheet for values.](https://docs.google.com/spreadsheets/d/1m__sGg2bLsOaXWI1v189VbDraBgXxethKf8tJQTBPms/edit#gid=138604873)

~~\* Dropdown must allow entry of custom values (values that are not in the dropdown). ~~
   ~~ \* Custom values will be saved in DB and start showing up in dropdown for others. Is this ok?~~

**Name/Description Types**
- Must be alphanumeric plus hyphen/underscore
- Should be pre-populated with dropdown from OCL:NameTypes and OCL:DescriptionTypes.[ Refer this sheet for values.](https://docs.google.com/spreadsheets/d/1m__sGg2bLsOaXWI1v189VbDraBgXxethKf8tJQTBPms/edit#gid=1197588315)

~~\* Dropdown must support entry of custom values~~

**Comment by AnjaliWadhwa** [comment]
For now, custom values will be saved in DB and start showing up in dropdown for others.

**Comment by AnjaliWadhwa** [comment]
<img width="953" alt="screen shot 2016-09-20 at 13 28 36" src="https://cloud.githubusercontent.com/assets/3176602/18662070/48e497ca-7f36-11e6-81c3-d1f52ac1ca8a.png">

**Comment by AnjaliWadhwa** [comment]
Entry of custom value will be a separate story.

**Comment by bhawnasingla** [comment]
Select Fully Specified as name type until we have multiple concept names #192

**Comment by AnjaliWadhwa** [comment]
This is working fine.
