### ISSUE TITLE
Data Backup

### ISSUE THREAD

**Issue by AnjaliWadhwa** [OpenConceptLab/oclapi#228]

**Comment by GauravButola** [comment]
Data backup is working fine. Periodical data backups have been setup as a cron job. Also another script has been setup in the deploy directory.

Taking manual backups using the backup script is straightforward - run the command:

`./mongo_backup.sh`

Backups are timestamped tar files stored in the `backups` directory in the `home` directory of the user.

To restore the database using the restore script - run the following command:

`./mongo_restore <backup_file_location`
