### ISSUE TITLE
Validate name on concept create

### ISSUE THREAD

**Issue by oalpay** [OpenConceptLab/oclapi#238]
Add following validations to run as default for all concepts on create
- Concept _preferred_name_ should be unique for same source and locale. Show "Concept preferred name should be unique for same source and locale" error if not valid.
- Concept requires at least one _fully_specified_name_. Show "Concept requires at least one fully specified name" error if not valid.

**Comment by guvencg** [comment]
hi Darius, 

this story is ready for UAT.  please check and give feedbacks. 

G.

**Comment by djazayeri** [comment]
I tested this out correctly prevents me from (a) having no fully-specified name, or (b) reusing the same locale-preferred name in the same source. (And it correctly only validates for the same locale.)

Two issues:

1. When it fails to save, all name fields are discarded; this is bad UX. (I'm fine if this gets logged as a defect card to be prioritized separately.)
2. I suggest two changes to this error message"Error occurred: Concept preferred name should be unique for same source and locale": (1) get rid of the words "Error occurred", and ideally replace these with an error icon; (2) ~~should~~ must.

**Comment by emrah-b** [comment]
@djazayeri I removed "Error occurred" however I chose not to put an error icon as I think it is redundant since the box already notifies error with its color. For #2, could you add the issue number here as a comment as to link these?

**Comment by djazayeri** [comment]
Error message looks good!

I just tested a little further and realized that we need the comparison to be case-insensitive. I.e. I was able to create a concept named "No description given" and also "no description given".

(Strictly speaking, _OpenMRS_ does case-insensitive comparisons for duplicate preferred names across concepts. @paynejd might choose to say that the Basic validation should allow it, but I don't think he'll say that.)

**Comment by paynejd** [comment]
Note that based on our discussions this week that name uniqueness
validation will shift over to the OpenMRS validation schema.

**Comment by fatmau** [comment]
These 2 validation rules are decided to move Open MRS schema, and a new validation is added to basic validation;

- requires at least one name regardless of name_type is

New story is created #262, so testing that story is enough. I move this one to done.
