### ISSUE TITLE
Create a source with OpenMRS validation schema

### ISSUE THREAD

**Issue by oalpay** [OpenConceptLab/oclapi#239]
OpenMRS requires some extra validation rules which may not be applicable for all the sources in OCL. A separate OpenMRS validation schema is going to be defined on the system and users will have the option to enforce it when creating a source.  The specific rules of the OpenMRS validation schema is going to be documented in upcoming issues. 
- select the OpenMRS validation option from a drop down on source create
  ![screen shot 2016-09-30 at 10 29 46](https://cloud.githubusercontent.com/assets/22494638/18984168/91c027e6-86f9-11e6-8d59-0e7eabd1e32c.png)
- view the validation schema of the source on view

**Comment by guvencg** [comment]
@darius, please check the story and push done if you're happy with this.

**Comment by djazayeri** [comment]
I just tried to create a User Source with OpenMRS validation on the staging server (user djazayeri) and I got this error: http://dpaste.com/3YMYNB8

However I _was_ able to create an organization, and to create a source in that org with OpenMRS validation.

(So, is this a data error in my user account, or is this a bug where this works for org sources but not user sources?)

**Comment by djazayeri** [comment]
@emrah-b fixed the configuration of the staging server, and I was able to successfully create both an org source and a user source with validation=OpenMRS
