### ISSUE TITLE
Fix email confirmation for new user account and forgotten password

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/oclapi#240]
Both emails say they are from "example.com", which causes them to get blocked by spam filters. The reset password email actually includes a link to example.com to reset the password (which obviously doesn't work!). This functionality is part of the django-allauth package which uses django.contrib.sites for the site/domain configuration. However, I cannot find anywhere which setting will let me set the correct domain in a way that will work for multiple environments. Sample emails are below. These two sites may help get you started:
- https://www.webforefront.com/django/setupdjangousercreation.html
- https://docs.djangoproject.com/en/1.10/ref/contrib/sites/
## Confirm Email Address

```
Subject: [example.com] Confirm E-mail Address
```

```
Hi lgatt,

Welcome to the Open Concept Lab. To finish activating the account for lgatt, please follow this link to confirm your email address:

http://staging.openconceptlab.org/accounts/confirm-email/fddd9e3b6583993678b6fcbe79e97ad0a2da1be8134f9567491c5eb17968ac2c/

Thanks,
The OCL Team
```
## Password Reset Email

```
Subject: [example.com] Password Reset E-mail
```

```
You're receiving this e-mail because you or someone else has requested a password for your user account at example.com.
It can be safely ignored if you did not request a password reset. Click the link below to reset your password.

http://example.com/accounts/password/reset/key/d-4fp-d76acbc900ad2935839b/

In case you forgot, your username is leahgatt.

Thanks for using our site!
```

**Comment by AnjaliWadhwa** [comment]
This is fixed in showcase, staging and production.

**Comment by GauravButola** [comment]
Similar to the default root superuser we're now creating a superuser for ocl_web as well with username - `admin`.

In a fresh deployment, admin will have to login and change the website url from the sites model to reflect the current environment.
