### ISSUE TITLE
OpenMRS Validation schema - validate names on concept create

### ISSUE THREAD

**Issue by oalpay** [OpenConceptLab/oclapi#241]
As a user
I want to **create** a concept with Open MRS schema (validation)
So that I can have a concept matching with Open MRS rules.

**Acceptance Criteria:**
- Concept should have exactly one preferred name per locale
- A preferred name can neither be a short name, an index/search term nor a voided name
- A name should be unique except for the short name

*Ignore voided name type validation of OCL concept*

**Comment by fatmau** [comment]
Darius: "we can ignore any rule about voided names when authoring a new concept"

**Comment by guvencg** [comment]
Emrah, when you're done with this , could you assign this to Darius to be reviewed and signed off pls?

**Comment by emrah-b** [comment]
There is bug: "A preferred name can neither be a short name, an index/search term nor a voided name" rule is not implemented

**Comment by djazayeri** [comment]
Good:
* I am not allowed to create a concept with two preferred names in English.
 * Should change the error text from "Custom validation rules require a concept to have exactly one preferred name" to "A concept must have one preferred name (per locale)".
* I am not allowed to mark a short name as the preferred name
 * Should change the error text from "Custom validation rules require a preferred name to be different than a short name" to "A preferred name cannot be a Short name"
* I am not allowed to create a concept which has 2 copies of the same name (one with type=fully-specified, the other with type=none).
 * Change error message from "Custom validation rules require all names except type=SHORT to be unique" to "All names for a concept must be unique, within a locale"

Bad:
* I am allowed to create a concept with two fully-specified names, but this should not be allowed by OpenMRS validation. (Maybe we forgot to document this before.)
* I am not allowed to create a concept that has a short name that is the same as a normal name. (It incorrectly gives the error message "Custom validation rules require a preferred name to be different than a short name")
 * A real scenario for this is a name with fully-specified name="milligrams", preferred syononym="mg" and short name="mg".
 * this is what the bullet point "A name should be unique except for the short name" is supposed to mean: you're not allowed to have two normal names with the same text, but you are allowed to have a normal name and a short name with the same text.
* I am allowed to create a concept with two short names
 * OpenMRS validation should only allow you to have one short name per locale , but this should not be allowed by OpenMRS validation.
 * [see example](https://staging.openconceptlab.org/users/djazayeri/sources/OMRS/concepts/241a/details/), though the mistake is not that both short names have the value "G", but that it allows two short names at all
 * I guess we failed to document this requirement properly
 * We need to crosswalk whether the validation we're implementing in stories here matches what's documented in [this validator method](https://github.com/openmrs/openmrs-core/blob/master/api/src/main/java/org/openmrs/validator/ConceptValidator.java#L60) in OpenMRS

Nice-to-fix:
* When I try to create a concept which has 2 copies of the same name, and I mark them both as preferred, the error message   is "Concept preferred name must be unique for same source and locale". However I would have expected to see the error message for one of the constraints I failed on this concept itself.
