### ISSUE TITLE
Run default validation with logging on console import

### ISSUE THREAD

**Issue by oalpay** [OpenConceptLab/oclapi#244]
As a user
I want to import concepts and mappings by bulk from console with basic validation schema
So that I can create concepts and mappings matching basic validation rules

Acceptance Criteria:
1. Validate all imported concepts / mappings one-by-one
2. If validation fails for any concept/mapping:
   - Skip the concept/mapping
   - Add relevant validation error and details to the validation error log
3. Continue until all concepts/mappings in the import list are through validation
4. Display log on console

**Comment by djazayeri** [comment]
I don't know how to log in to the server and import from the console, so I can't test this yet. Maybe @paynejd and I should pair on this?

**Comment by paynejd** [comment]
Darius, let's setup a time to test this together.

**Comment by paynejd** [comment]
This is running as expected for the validation tests that I attempted.
