### ISSUE TITLE
Validate lookup attributes on concept create

### ISSUE THREAD

**Issue by oalpay** [OpenConceptLab/oclapi#245]
As a user
I want to **create/edit** a concept via UI, console or API
So that I can have a concept matching with basic validation rules.

**Acceptance Criteria:**
Below parameters should have only possible values listed at spreadsheet; 
- concept class
- concept datatype
- concept name type
- concept description type

https://docs.google.com/spreadsheets/d/1m__sGg2bLsOaXWI1v189VbDraBgXxethKf8tJQTBPms/edit#gid=513895808

**Comment by fatmaurek** [comment]
hi,

i am Fatma, new BA of this project, working half time at this project. i have a few questions about this story;

we have found below possible values from codebase for 5 attributes (these attributes were decided at previous e-mails between you and Osman) and i've some questions between the lines. could you please check and share your comments? 

by the way, if there is any other attribute that should be validated, could you specify? 

thanks & cheers

Attribute: Concept Class
- Aggregate Measurement
- Anatomy
- ConvSet
- Diagnosis
- Drug
- Drug form
- Finding
- Frequency
- Health Care Monitoring Topics
- Indicator
- LabSet
- Medical supply
- MedSet
- Misc
- Misc Order
- Organism
- Pharmacologic Drug Class
- Procedure
- Program
- Question
- Radiology/Imaging Procedure
- Specimen
- State
- Symptom
- Symptom/Finding
- Test
- Units of Measure
- Workflow

Attribute: Concept Datatype
- Boolean
- Coded
- Complex
- Date
- Datetime
- Document
- None
- Numeric
- Rule
- Structured Numeric
- Text
- Time

Attribute: Concept Name Type
- FULLY_SPECIFIED
- SHORT

Attribute: Concept Description Type
- Unknown (we could not find any possible value for this attribute, so if there is any possible value could you please share? if the is no value, should we still validate this attribute and in terms of what?)

Attribute: Mapping Type
- Associated finding (we are not sure if it is used, what do you think?)
- BROADER-THAN
- CONCEPT-SET
- NARROWER-THAN
- Q-AND-A
- SAME-AS
- IS-SET-MEMBER-OF

**Comment by djazayeri** [comment]
This issue overlaps very significantly with what is listed in #217. The possible values should be given in [this sheet](https://docs.google.com/spreadsheets/d/1m__sGg2bLsOaXWI1v189VbDraBgXxethKf8tJQTBPms/edit#gid=138604873) (linked from that other issue). At first thought I would close this issue as a duplicate, and work on the other...

The idea is that there should be sources defined under the OCL organization to represent these pick lists.

(I think there's a future story about further allowing the admin of a source to override which pick list they use, e.g. CIEL might want a different pick list vs OCL's default, but this is out of scope for the first story.)

**Comment by fatmau** [comment]
on hold! after story #217 completed, we will check again whether validation is still needed or not.

**Comment by paynejd** [comment]
#217 is now in UAT, however, I would still hold off on this ticket until
end of October, because the India team is still making significant changes
to the concept authoring functionality.

**Comment by fatmau** [comment]
These validation rules should be moved to Open MRS with new story #365.

I believe; after completing that story, testing for both basic and Open MRS is more time saving. That's why I assigned this story to me, waiting for the next one.

**Comment by djazayeri** [comment]
I tested this via the REST API and it behaves as expected. Good work!

I would prefer a change to the wording of the error messages (though, this is low priority since the UI already prevents you).

Currently the error messages are like "Data type should be valid attribute", but I would prefer this to say "Invalid data type". (And similar for class, name type, and description type.)

**Comment by djazayeri** [comment]
I tested this on staging and I did _not_ get the new error messages that I see in @emrah-b 's commits from 19-20 days ago. Maybe this isn't deployed yet?

**Comment by djazayeri** [comment]
I noticed one more small error, which is that regardless of which field I make invalid, it always reports the error being on the "names" field, e.g. `{"non_field_errors": ["An error occurred while saving new concept version."], "names": ["Invalid data type"]}`

**Comment by emrah-b** [comment]
This is fixed now (I'll make sure it's deployed to staging)

**Comment by fatmau** [comment]
i think this story is ok now, could you please check again @djazayeri ?
