### ISSUE TITLE
OpenMRS Validation schema - validate description on concept create

### ISSUE THREAD

**Issue by oalpay** [OpenConceptLab/oclapi#246]
As a user
I want to create a concept with Open MRS schema (validation)
So that I can create a concept matching with Open MRS rules.

**Acceptance Criterias:**
- at least one description is required for a concept

**Comment by emrah-b** [comment]
![tpbg160603-59](https://cloud.githubusercontent.com/assets/838431/19378387/e88c8ce4-91f4-11e6-9fa7-d17fcb411e59.jpg)

**Comment by djazayeri** [comment]
Unfortunately in between the time this story was played and now, OpenMRS changed its mind, and this validation is now a mistake. (See [Discuss](https://talk.openmrs.org/t/important-we-started-requiring-concept-descriptions-but-this-was-a-mistake/8517) and [ticket](https://issues.openmrs.org/browse/TRUNK-2809) for OpenMRS.)

We need to remove this validation, i.e. OpenMRS allows you to have concepts with zero descriptions.

**Comment by emrah-b** [comment]
@djazayeri I move this back to UAT, for you to test that we dropped the validation rule

**Comment by paynejd** [comment]
Assuming that we should still not allow empty descriptions however?

**Comment by emrah-b** [comment]
@paynejd actually it's not a part of basic validation. we didn't create a story based on this comment on the validations spreadsheet

<img width="1036" alt="screen shot 2016-11-04 at 10 30 52" src="https://cloud.githubusercontent.com/assets/838431/19997805/fca4206c-a279-11e6-800a-c714d7d78683.png">

Should we add this to basic validation?

**Comment by djazayeri** [comment]
This works correctly in the UI. (I.e. I am allowed to save a concept without giving a description.)

However what is saved on the back end is not what I want. When I refetch it via the REST API I get:

```
  ...
  "descriptions": [
    {
      "uuid": "a465ad50cab944c2967e2cf763660b88",
      "external_id": null,
      "description": "",
      "locale": "en",
      "locale_preferred": true,
      "description_type": "None",
      "type": "ConceptDescription"
    }
  ],
  ...
```

This is not desirable.

**Comment by emrah-b** [comment]
@djazayeri actually basic validation now requires that all concepts have a description. So if you agree I think makes sense to mark this one as done.

**Comment by paynejd** [comment]
Basic validation should not require a description, it should require that
descriptions are non-empty. Meaning, empty descriptions should be
discarded.

OpenMRS may require a description?

**Comment by emrah-b** [comment]
Regarding this issue, gathering what @djazayeri and @paynejd said:
- @djazayeri: If your comment about creating a null description is a must-have, we can revisit it.  Otherwise we can mark it as done?
- @paynejd : we'll update #303 and revisit

Does that resolve the issue around descriptions?
