### ISSUE TITLE
Creation of new source version throws JSONDecodeError

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/oclapi#247]
See error screenshot below. This occurred here: http://showcase.openconceptlab.org/users/paynejd/sources/JonsSource/versions/new/

I created a new source version under a user source with ID of "v3" and description of "v3" resulting in this error:

![image](https://cloud.githubusercontent.com/assets/1189689/18997387/cc2e92bc-873c-11e6-885f-8e781737cffb.png)

However, if I manually change the URL to go back to the versions tab of the source, it shows that the source version was created just fine.

**Comment by AnjaliWadhwa** [comment]
This is fixed and working fine now.
