### ISSUE TITLE
'active_concepts' and 'active_mappings' values are not saved in Head version of Source

### ISSUE THREAD

**Issue by AnjaliWadhwa** [OpenConceptLab/oclapi#252]
When I create version of source it is saved but not in HEAD version.

**Comment by mKadiyan** [comment]
active_concepts and active_mappings was the requirement related to  export functionality and since we can't export 'HEAD' so as of now it's implemented only for Version creations

**Comment by mKadiyan** [comment]
since head is dynamically changing HEAD, active_concepts and active_mappings are not stored for this but calculated dynamically.

**Comment by AnjaliWadhwa** [comment]
This is working fine
