### ISSUE TITLE
User search always returns zero results if criteria used

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/oclapi#254]
For example, this works fine:
```
http://api.showcase.openconceptlab.org:8000/users/
```

Any value for `q` will return zero results:
```
http://api.showcase.openconceptlab.org:8000/users/?q=paynejd
http://api.showcase.openconceptlab.org:8000/users/?q=Rohit
```

Users are supposed to be indexed by username, first name, and last name

**Comment by snyaggarwal** [comment]
This happens in existing app (staging.openconceptlab.com and openconceptlab.com)
Because of a typo in user solr search fields in views.
Fixed now!

**Comment by paynejd** [comment]
Thank you! Tested and this is working correctly.
