### ISSUE TITLE
Edit concept data is not saved in DB

### ISSUE THREAD

**Issue by AnjaliWadhwa** [OpenConceptLab/oclapi#255]
When user edit / update concept, the data is not saved in DB.

Example: when concept is retired in the UI, it does not save the "Retire reason" field as the "Update comment", instead it simply records "Concept was retired". Recommendation is to record the user's action in brackets before the user's comment. For example: "[Retired] Concept was no longer in use"

Note: This is already fixed for Extras.

**Comment by mKadiyan** [comment]
Is this user story is related to Concept Edit or Concept Retire ?
What are the fields that are not updated ?
please clarify..

**Comment by AnjaliWadhwa** [comment]
It is a bug about 'Retire reason' is not saved when concept is retired. We need to save it in 'update comment' field in DB and also show it in History tab.
