### ISSUE TITLE
Source "supported_locales" is displaying "default_locale" on user/org source details

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/oclapi#256]
On the user/org source details page, "supported_locales" is displaying the value of "default_locale" instead of "supported_locales". When editing the source, however, the `supported_locales` field is displayed and saved correctly.

![image](https://cloud.githubusercontent.com/assets/1189689/19109181/ee07aeaa-8afc-11e6-8666-143482d1ad0c.png)

![image](https://cloud.githubusercontent.com/assets/1189689/19109194/f74ee47e-8afc-11e6-93c1-33c709785e8a.png)

**Comment by AnjaliWadhwa** [comment]
This is fixed and working fine. 

Also fixed multiple values for 'supported_locale' were not being displayed on UI. Now we show all the values as comma separated.

<img width="852" alt="screen shot 2016-10-06 at 17 14 51" src="https://cloud.githubusercontent.com/assets/3176602/19151121/9bca2806-8be8-11e6-82c2-1574d1aa5438.png">

**Comment by paynejd** [comment]
Tested and is working correctly!
