### ISSUE TITLE
Make UI tests run locally

### ISSUE THREAD

**Issue by emrah-b** [OpenConceptLab/oclapi#260]
Currently UI tests need deployment, cannot be run locally

**Comment by AnjaliWadhwa** [comment]
Please note that we can run UI tests locally. To do that we need to update 
'baseUrl:' in 'ocl_web/tests/ui_tests/conf.js' to localhost.

**Comment by cengizIO** [comment]
@AnjaliWadhwa correct but not enough.

Current test specs assume that there's a certain valid user login (see [test_data.json](https://github.com/OpenConceptLab/ocl_web/blob/master/ocl_web/tests/ui_tests/fixtures/test_data.json)) present on API side, which is not created by default when someone brings development environment up.

Also there are two failures with `POST /orgs/EthiopiaMoH-test-KOAsI/collections/WHO-testKOAsI/references/new/` and `DELETE /users/awadhwa1/collections/WHO-testlu/V1/` requests on ui tests, which seems to be isolated to only local runs. Doesn't seem to be reproducible on pipeline.

I think we need to investigate these for the sanity of future contributors 😄

**Comment by AnjaliWadhwa** [comment]
I have updated the tests. 

* You can now run tests with below command from 'ocl_web':

       `browser=chrome env=local username=<username> password=<pwd>             ./node_modules/protractor/bin/protractor ./ocl_web/tests/ui_tests/conf.js`

    Note: You will have to manually signup and have valid credentials though.

* By default it runs on showcase env in headless mode using phantomjs with my credentials. Below is the command for it 

   `./node_modules/protractor/bin/protractor ./ocl_web/tests/ui_tests/conf.js`

**Comment by snyaggarwal** [comment]
@emrah-b -- the simple way to solve the problem is to create a user as background step (beforeAll) and signup with it. Dont think we need more on this after what @AnjaliWadhwa did.
