### ISSUE TITLE
Set permissions for "root" user

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/oclapi#267]
Root user should be allowed to view and edit all data

**Comment by paynejd** [comment]
Highest priority permissions changes are:
* Ability to edit user profiles and edit organization membership

**Comment by mKadiyan** [comment]
users with is_staff=True can see and edit orgs resources
 
Open points:
 - does web or api support user profiles editing. if yes, user profiles are edited currently.

**Comment by paynejd** [comment]
Question: Does "root" user have an API token?

2 other actions that "root" user should be able to do:
* Download JSON export file
* Download full CSV files for any repository, same as the owner/member

**Comment by mKadiyan** [comment]
- user can be promoted to staff using api too. (without directly changing the mongodb using /admin url at api)
- "root" with username as "root" is having the api token , other users which are promoted to staff have their own token like normal user.

**Comment by AnjaliWadhwa** [comment]
User with 'is_staff' set now can do all actions on Org, Sources, Collections, etc. Please note that all these permissions are applicable to resources under Org.
