### ISSUE TITLE
OpenMRS - run validation with extend logging [on bulk import from console]

### ISSUE THREAD

**Issue by fatmau** [OpenConceptLab/oclapi#298]
As a user
I want to import concepts and mappings by bulk from console with OpenMRS schema
So that I can create concepts and mappings matching basic validation rules

Acceptance Criteria:
1. Validate all imported concepts / mappings one-by-one
2. If validation fails for any concept/mapping:

Skip the concept/mapping
Add relevant validation error and details to the validation error log
Continue until all concepts/mappings in the import list are through validation
Display log on console

**Comment by paynejd** [comment]
This is working correctly for each of the validation rules that I tested.
