### ISSUE TITLE
create collection with OpenMRS validation [on create collection]

### ISSUE THREAD

**Issue by fatmau** [OpenConceptLab/oclapi#300]
OpenMRS requires some extra validation rules which may not be applicable for all the collections in OCL. A separate OpenMRS validation schema is going to be defined on the system and users will have the option to enforce it when creating a collection.  The specific rules of the OpenMRS validation schema is going to be documented in upcoming issues. 
- select the OpenMRS validation option from a drop down on collection create
  ![91c027e6-86f9-11e6-8d59-0e7eabd1e32c](https://cloud.githubusercontent.com/assets/123910/19727027/52988b9c-9b96-11e6-9c2b-24b6d4ffcd70.png)
- view the validation schema of the collection on view

**Comment by fatmau** [comment]
guys, do you consider "collection edit" or should we create a new story for edit? @cengizIO  & @kavasoglu

**Comment by kavasoglu** [comment]
@fatmau i tested  create and edit actions, seems ok for both ;)
