### ISSUE TITLE
Basic - attributes not empty on concept/map create

### ISSUE THREAD

**Issue by fatmau** [OpenConceptLab/oclapi#303]
Acceptance Criteria
- When creating a concept, given any source:
   - Concept name cannot be empty
   - Concept Description cannot be empty
   - Concept Datatype cannot be empty
   - Concept Class cannot be empty
- When creating a mapping, given any mapping:
   - Map source cannot be empty
   - Map target cannot be empty

**Comment by emrah-b** [comment]
@fatmau what should we do about this one?
