### ISSUE TITLE
Open MRS - Validate lookup attributes on map create

### ISSUE THREAD

**Issue by fatmau** [OpenConceptLab/oclapi#317]
As a user
I want to **create/edit** a mapping via UI, console or API
So that I can create a mapping matching with Open MRS validation rules.

**Acceptance Criteria:**
Below parameters should have only possible values listed at related dictionary source;
- mapping type --> https://openconceptlab.org/orgs/OCL/sources/MapTypes/concepts/

At UI, create dropdown for both Basic and Open MRS, which are feed by related dictionary sources.

https://docs.google.com/spreadsheets/d/1m__sGg2bLsOaXWI1v189VbDraBgXxethKf8tJQTBPms/edit#gid=513895808

**Comment by paynejd** [comment]
This is working as expected
