### ISSUE TITLE
#238: Preferred name uniqueness per source and locale works incorrectly

### ISSUE THREAD

**Issue by emrah-b** [OpenConceptLab/oclapi#334]
@paynejd reported this:

**How to reproduce:**
1. Create a source S1
2. Create a concept C1 in S1, let C1 have the names :
    * (name:name1, locale:fr, preferred:false)
    * (name:name2, locale:en, preferred:false, type: Fully Specified)
3. Create a concept C2 in S1, let C2 have the names:
    * (name: name1, locale:en, preferred: True, type: Fully Specified)
4. Observe validation error: Concept preferred name must be unique for same source and locale

 C2's preferred name for en locale is unique for the source and locale, and should pass the validation

**Comment by fatmau** [comment]
we should add new items from the comments of #241

**Comment by djazayeri** [comment]
When I try to do this (in an OpenMRS-validated source) I get the error message:
"Custom validation rules require fully specified name should be unique for same locale and source"

**Comment by djazayeri** [comment]
I tested again (after newer code was deployed) and this worked correctly for a source with OpenMRS Validation.
