### ISSUE TITLE
#241 - Additional Development Issues

### ISSUE THREAD

**Issue by fatmau** [OpenConceptLab/oclapi#335]
According to Darius' comments about story #241, below criteria list is generated for Open MRS schema.

**Acceptance Criteria:**

- Concept can have only one _fully-specified name_ per locale 
    - Error message should be "A concept may not have more than one fully specified name in any locale"
- Concept should have at least one _fully-specified name_
    - Error message should be "A concept must have at least one fully specified name (across all locales)"
- Concept should have 1 or 0 _short name_ per locale
    - Error message should be "A concept cannot have more than one short name in a locale"
- Concept should have exactly one _preferred name_ per locale
    - Error message should be "A concept may not have more than one preferred name (per locale)"
- A preferred name can neither be a short name, nor an index/search term
    - Error message should be "A short name cannot be marked as locale preferred" 
- Concept should not have two non-short names with the same text but it could have a short name and a non-short name with the same text within source and locale.
    - Error message should be "All names except short names must unique for a concept and locale"

**Comment by djazayeri** [comment]
(I made minor changes to the wording of the first comment on this issue, but didn't change the meaning.)
