### ISSUE TITLE
Missing edit warning #277

### ISSUE THREAD

**Issue by fatmau** [OpenConceptLab/oclapi#338]
At story #277 when trying to delete fully specified name of a concept, system acts like concept is updated (but not save the update to DB) and does not show an error message.

Normally; Whenever a required field is deleted, system should behave like:
- show error message
- do not allow user to complete action (stays on same page until cancel button clicked)
- do not save updates to DB

**Comment by djazayeri** [comment]
I just tested this, and it is still broken. (I.e. it appears to save, but does not actually update the db.)

(Could it be that we don't have the right code running on the staging server?)

**Comment by djazayeri** [comment]
After new code was deployed, I tested this and it worked. (I.e. I removed a concept's only name and tried to save, and it correctly showed me an error message.)
