### ISSUE TITLE
Set up production environment

### ISSUE THREAD

**Issue by MisterNando** [OpenConceptLab/oclapi#34]
Aaron, please let me know where you would like to setup the production environment. Happy to do Rimuhosting (the current server environment) or to switch to AWS.

**Comment by MisterNando** [comment]
Estimates

Original - N/A
Updated - 8h

**Comment by paynejd** [comment]
PK will most likely take care of this, as he has moved everything into deployment scripts. PK please confirm.

**Comment by pkshiu** [comment]
Yes I will take care of this .

Sent via Siri
