### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by MisterNando** [OpenConceptLab/oclapi#36]
From the original SOW:

API technical and user documentation including (preferably on Wiki):
* User documentation with syntax for API calls (can use existing documentation as starting point, but should reflect exactly what has been implemented)
* Technical documentation describing how the API code functions
* Technical documentation on running API test battery
* Inline documentation for API code specifications
* Short guide on setting up API development environment
* Short guide on Solr configuration

**Comment by MisterNando** [comment]
Estimates

Original - N/A
Updated - 8h

**Comment by paynejd** [comment]
Replaced with more specific tickets
