### ISSUE TITLE
Validation updates on content create/edit

### ISSUE THREAD

**Issue by fatmau** [OpenConceptLab/oclapi#362]
Below validations, which are developed at #238, should be removed from basic validation and should be added to Open MRS schema on concept create/edit.
- "preferred name" should be unique (by locale) within a source
- concept requires at least one "fully_specified_name"

Below validation should be added to basic validation;
- concept requires at least one name regardless of name_type. the error message is "A concept must have at least one name."

**Comment by djazayeri** [comment]
(It's possible that the latest API code isn't deployed to staging as I'm testing this now...)

The first two validations seem to be have correctly moved from Basic validation to OpenMRS validation.

> concept requires at least one name regardless of name_type. the error message is "A concept must have at least one name."

When I try to save a concept like this (by editing, or doing it via the API) I get a 500 status error, instead of a nice error message.

**Comment by djazayeri** [comment]
> concept requires at least one name regardless of name_type. the error message is "A concept must have at least one name."

When I try to create a new concept with no names through the UI (clicking the trash icon on the field's only name) I am (correctly) blocked from doing this, however the error message at the top of the page is "This field is required" without any indication of which field is required.

When I try to create a new concept with no names via REST, I similarly get the response `{"names": ["This field is required."]}`

When I try to update an existing concept to remove its name I get ugly errors (status 500 with django-generated html).

Via the web the error message says: JSONDecodeError Expecting value: line 2 column 1 (char 1)

Via REST I get back html which has this main message:
The model &#39;&lt;ConceptVersion: --TEMP--&gt;&#39; has an empty model_attr &#39;display_name&#39; and doesn&#39;t allow a default or null value.

**Comment by fatmau** [comment]
- at least one fully specified name : in concept!!!

**Comment by emrah-b** [comment]
@djazayeri I updated the message, and the mismatch of behavior between concept create and edit pages

**Comment by djazayeri** [comment]
Good: when I try to create a new concept with no name, I get a helpful error message that says a name is required.

Bad: when I try to edit a concept to remove its only name (using the trash icon) I still get an ugly stack trace with JSONDecodeError Expecting value: line 2 column 1 (char 1)

**Comment by emrah-b** [comment]
@djazayeri it was a deployment issue, tested it on staging, please have a go

**Comment by djazayeri** [comment]
I tested again and:

* Editing now works correctly (when I remove the only name and try to save it says "a concept must have at least one name").
* Creating a concept has regressed a bit. When I try to create a concept with no name it says "This field is required." without visually indicating which field.

**Comment by djazayeri** [comment]
Tested and the error messages are now correct for both creating and editing.
