### ISSUE TITLE
Concept Create - Performance Issue

### ISSUE THREAD

**Issue by fatmau** [OpenConceptLab/oclapi#378]
Concept Create page loads in 5 seconds, this needs to be enhanced

**Comment by molgun** [comment]
We think that the problem is about locale fetching. When client make request to read locales, API first reads all locales ids from from Solr then fetch all these locales from MongoDB by ID. This is an expensive operation. I think we should read these values from MongoDB or Solr. Not both.

**Comment by burakince** [comment]
API first reads all locales IDs from Apache Solr then fetch all these locales from MongoDB one by one.
