### ISSUE TITLE
Concept / Global Search / Search, select and cancel

### ISSUE THREAD

**Issue by fatmau** [OpenConceptLab/oclapi#406]
As a user
I want to select and cancel any concept to collection
So that I will have the freedom to continue or discontinue to do this action.

**Dependency:**

- N/A

**Acceptance Scenario:**

| No  | Given  | When  | Then  |
| ------------- | ------------- | ------------- | ------------- |
| 1 | I searched for concept with one or multiple result | I clicked on "+ Add to Collection" link  | the result list will become a selectable table |
| 2 | Scenario No 1  | I click on "Select All" button  | All concepts on the page will be selected  |
| 3 | Scenario No 2  | I click on "Unselect All" button  | All concepts on the page will be unselected  |
| 4 | Scenario No 3  | I click on "Cancel" button  | Page returns to initial form (only a list without select ability)  |

**Mock-ups:**

- Mock-ups can be found at this URL --> https://marvelapp.com/14d1eb3/screen/18172736
- Cancel button should appear only when there is no selected concept.
-Check the link below to see the pages
https://drive.google.com/drive/u/0/folders/0B2RCqE113zNxNm9wdThQVXVvaEk

**Technical Assumptions:**

- This is the first story of UI part
- No need to consider what happens after concepts are selected.

**Comment by djazayeri** [comment]
This story is done as-written. However we want to change the behavior so this works the same way as is currently working when selecting concepts within a collection. (The checkboxes are always there; checking any box activates the Add To Collection button.)

**Comment by berkansahan** [comment]
Here are the links to see updated version of the story. Checkboxes are always there and Add to Collection button is just next to the checkboxes as the other pages (to have continuity)
-Mock-ups: https://marvelapp.com/14d1eb3/screen/25608668 
-Drive: https://drive.google.com/drive/u/0/folders/0B2RCqE113zNxNm9wdThQVXVvaEk
