### ISSUE TITLE
Explore improving solr indexing performance

### ISSUE THREAD

**Issue by emrah-b** [OpenConceptLab/oclapi#416]
There is already some work done on this. We explored:
- Increasing ramBufferSize
- Increasing SOLR_HEAD
- Set HAYSTACK worker count to 5 instead of 1 on the import scripts

Deliverable of this issue would be:
- Performance improvement or
- A report of what's explored, what worked

**Comment by molgun** [comment]
Hi guys,

On second thought, I think we don't need this since we made Solr index persistent to disk. We are not going to make bulk import to Solr on every deploy. What do you think? @hevalberknevruz @burakince

**Comment by paynejd** [comment]
If this change is easy please go forward with it. Importing new releases of
CIEL may be a monthly event.
