### ISSUE TITLE
Create a loading indicator

### ISSUE THREAD

**Issue by emrah-b** [OpenConceptLab/oclapi#420]

**Comment by berkansahan** [comment]
loader gif is designed for OCL. pls see the attachment or check the link to see and download different sizes (256px-132px-64px-32px) of loading gif.
https://drive.google.com/drive/u/0/folders/0B2RCqE113zNxVXJBakhHdGhoWDg
[OCL_loader gif.zip](https://github.com/OpenConceptLab/oclapi/files/749994/OCL_loader.gif.zip)
