### ISSUE TITLE
Concept / Global Search / Search, select and add (to existing collection) - Add to Collection

### ISSUE THREAD

**Issue by fatmau** [OpenConceptLab/oclapi#423]
As a user
I want to select and add any concept to collection
So that I will select a collection and cancel the action.
**Dependency:**

- #406 

**Acceptance Scenario:**

| No  | Given  | When  | Then  |
| ------------- | ------------- | ------------- | ------------- |
| 1 | I searched for concept with one or multiple result | I select one or multiple results  | Add to Collection appears |
| 2 | Scenario No 2  | I click the dropdown | I see all my existing collections on the list  |
| 3 | Scenario No 3  | I click on the page besides dropdown or in dropdown  | Page returns initial form. |

**Mock-ups:**

- Mock-ups can be found at this URL --> https://marvelapp.com/project/1121018/screen/25020781
-Check the link below to see the pages
https://drive.google.com/drive/u/0/folders/0B2RCqE113zNxNm9wdThQVXVvaEk

**Technical Assumptions:**

- This is for the Logged-in User.
- Organisation and personal collections should have different backgrounds.
- No need to consider what is going to happen after save action has clicked.
- When the user refresh the page, it returns Scenario 1.

**Comment by djazayeri** [comment]
This works 95%.
If I cancel (by closing the dropdown or clicking outside it) any radio button selection in the dropdown is preserved the next time I open it. I would expect the selection to be discarded. (This is not a blocker for release.)

**Comment by berkansahan** [comment]
To see unselected radio button whenever you only close the dropdown may irritate user easily. There are several reasons: 
 - you may close the dropdown accidentally.
- the whole action is not completed
- you may change or add something, then continue to action. etc.

Because of this reasons, we do not suggest to implement it here.

(ps: this is about before clicking "Add" action)

What do you think ?  @djazayeri

**Comment by djazayeri** [comment]
Okay, it makes sense that

* when you Confirm, it resets the radio and checkbox state
* if you cancel, it can preserve the state

**Comment by paynejd** [comment]
This is working correctly, except that if I actually click on the "Cancel" button in the confirmation window, it clears out my checkboxes.

**Comment by berkansahan** [comment]
If the user comes to the stage "Cancel" or "Confirm", that means it is almost end of the road. We do suggest to clear all checkboxes when the user "cancel" the action because it is in confirmation box. What do you think? @paynejd

**Comment by paynejd** [comment]
My suggestion is to "cancel the addition of selected resources to the
collection". Not "cancel action" plus "clear selection". Because then I'd
have to start over.

**Comment by berkansahan** [comment]
Now, when I click "Cancel" button, it does not clear my checkboxes @paynejd
