### ISSUE TITLE
Concept / Global Search / Search filter to Collection dropdown

### ISSUE THREAD

**Issue by fatmau** [OpenConceptLab/oclapi#424]
As a user
I want to search any collections in dropdown
So that I will filter specific collection in dropdown.

**Dependency:**

- N/A

**Acceptance Scenario:**

| No  | Given  | When  | Then  |
| ------------- | ------------- | ------------- | ------------- |
| 1 | I search any concept in global search | I select one or multi results | Add to Collection button appears |
| 2 | I see any concept detail | I click 'Add to Collection' button | I see all my existing collections on the list |
| 3 | Scenario No 3  | I write "Eth" in search bar in dropdown | I see the collections which includes ''eth'' in  |

**Mock-ups:**

-Check the link below to see the pages
https://drive.google.com/drive/u/0/folders/0B2RCqE113zNxNm9wdThQVXVvaEk

**Technical Assumptions:**

- This is for the Logged-in User.
- No need to consider If the user has no collection.

**Comment by paynejd** [comment]
This is really cool!! And works as specified.
