### ISSUE TITLE
Concept / Detail / Add to collection (without collection)

### ISSUE THREAD

**Issue by fatmau** [OpenConceptLab/oclapi#428]
As a user
I want to add my selected concept to collection
So that I will see information when I do not have existing collection.

**Dependency:** 
-N/A

**Acceptance Scenario:**

| No  | Given  | When  | Then  |
| ------------- | ------------- | ------------- | ------------- |
| 1 | I see any concept detail | I click 'Add to Collection' button | I list what I have in my collection |
| 2 | Scenario No 1  | I do not have existing collection | Information (create a collection in your profile) will be in the dropdown |
| 3 | Scenario No 2  | I click somewhere else beside dropdown | Page returns inital form |

**Mock-ups:**

- Mock-ups can be found at this URL --> https://marvelapp.com/14d1eb3/screen/25357973
-Check the link below to see the pages
https://drive.google.com/drive/u/0/folders/0B2RCqE113zNxNm9wdThQVXVvaEk

**Technical Assumptions:**

- This is for the Logged-in User.
- No need to consider If the user has collection.

**Comment by djazayeri** [comment]
On this screen the popup grows to be very very long if you have access to lots of collections.
Instead it should behave just like on the global search page (where the popup size is fixed, and it has internal scrolling).

**Comment by djazayeri** [comment]
If I go to a specific concept version (e.g. https://staging.openconceptlab.org/users/djazayeri/sources/OMRS/concepts/Node/58d4cd391bee0d0051b881c7/details/) and I do Add to Collection from there, it shows me the message "Added the latest versions of concept to the collection. Future updates will not be added automatically" Instead I would have expected the version whose page I was on to be added.

**Comment by djazayeri** [comment]
Scrolling issue has been fixed.
