### ISSUE TITLE
Mapping / Global Search / Search, select and cancel

### ISSUE THREAD

**Issue by fatmau** [OpenConceptLab/oclapi#434]
As a user
I want to select and add any mapping to collection
So that I will select a collection and cancel the action.
**Dependency:**

- #435   

**Acceptance Scenario:**

| No  | Given  | When  | Then  |
| ------------- | ------------- | ------------- | ------------- |
| 1 | I searched for mapping with one or multiple result | I select one or multiple results  | Add to Collection appears |
| 2 | Scenario No 1  | I click the dropdown | I see all my existing collections on the list  |
| 3 | Scenario No 2  | I select one of the user collection  | Save button returns actively clickable |
| 4 | Scenario No 3 | I click save button  | Info box appears on the page. |
| 5 | Scenario No 4  | Info box appears on the page | I click Cancel button  |
| 6 | Scenario No 5  | I click the Cancel button | Page returns initial form  |

**Mock-ups:**

- Mock-ups can be found at this URL --> https://marvelapp.com/---
-Check the link below to see the pages
https://drive.google.com/drive/u/0/folders/0B2RCqE113zNxNm9wdThQVXVvaEk

**Technical Assumptions:**

- This is for the Logged-in User.
- Organisation and personal collections should have different backgrounds.
- No need to consider what is going to happen after 'Confirm' button has clicked.
- When the user refresh the page,it returns initial form.
- Code of yellow colour is: **#F8F0BF**

**Comment by paynejd** [comment]
This works correctly, except that when I actually click on the Cancel button in the confirmation window, it clears my checkboxes.

(Sorry, I've said this in several places now!)
