### ISSUE TITLE
Mapping / Global Search / Search, select and add (without collection)

### ISSUE THREAD

**Issue by fatmau** [OpenConceptLab/oclapi#435]
As a user
I want to select and add any mapping to collection
So that I will see information when I do not have existing collection.

**Dependency:**

- N/A

**Acceptance Scenario:**

| No  | Given  | When  | Then  |
| ------------- | ------------- | ------------- | ------------- |
| 1 | I searched for mapping with one or multiple result | I select one or multi results | Add to Collection button appears |
| 1 | I see any concept detail | I click 'Add to Collection' button | I see all my existing collections on the list |
| 2 | Scenario No 1  | I do not have existing collection | Information will be in the dropdown |
| 3 | Scenario No 2  | I click somewhere else beside dropdown | Page returns initial form |

**Mock-ups:**

- Mock-ups can be found at this URL --> https://marvelapp.com/---
-Check the link below to see the pages
https://drive.google.com/drive/u/0/folders/0B2RCqE113zNxNm9wdThQVXVvaEk

**Technical Assumptions:**

- This is for the Logged-in User.
- No need to consider If the user has collection.

**Comment by paynejd** [comment]
This works correctly.
