### ISSUE TITLE
Mapping / Repository Search / Search, select and cancel

### ISSUE THREAD

**Issue by fatmau** [OpenConceptLab/oclapi#437]
As a user
I want to select and cancel any mapping to collection
So that I will have the freedom to continue or discontinue to do this action.

**Dependency:**

- N/A

**Acceptance Scenario:**

| No  | Given  | When  | Then  |
| ------------- | ------------- | ------------- | ------------- |
| 1 | I list the mappings | I select any mapping with checkboxes  | Disabled 'Add to Collection' button becomes enabled (clickable) |
| 2 | Scenario No 1  | I click on "Select All" button  | All concepts on the page will be selected  |
| 3 | Scenario No 2  | I click on "Unselect All" button  | Enabled 'Add to Collection' button becomes disabled |

**Mock-ups:**

- Mock-ups can be found at this URL --> https://marvelapp.com/project/---
-Check the link below to see the pages
https://drive.google.com/drive/u/0/folders/0B2RCqE113zNxNm9wdThQVXVvaEk

**Technical Assumptions:**

- No need to consider what happens when 'Add to collection' button is clicked.

**Comment by paynejd** [comment]
This works correctly -- except that checkboxes are cleared when I click on the "cancel" button
