### ISSUE TITLE
Mapping / Repository Search / Search, select and add (without collection)

### ISSUE THREAD

**Issue by fatmau** [OpenConceptLab/oclapi#438]
As a user
I want to select and add any mapping to collection
So that I will see information when I do not have existing collection.

**Dependency:**

- #437   

**Acceptance Scenario:**

| No  | Given  | When  | Then  |
| ------------- | ------------- | ------------- | ------------- |
| 1 | I list the mappings | I select any concept with checkboxes  | Disabled 'Add to Collection' button becomes enabled (clickable) |
| 2 | Scenario No 1  | 'Add to Collection' button becomes enabled | Add to Collection link becomes a dropdown  |
| 3 | Scenario No 2  | I do not have existing collection | Information will be in the dropdown  |
| 4 | Scenario No 3  | I unselect all the concepts  | 'Add to Collection' button becomes disabled

**Mock-ups:**

- Mock-ups can be found at this URL --> https://marvelapp.com/---
https://drive.google.com/drive/u/0/folders/0B2RCqE113zNxNm9wdThQVXVvaEk

**Technical Assumptions:**

- This is for the Logged-in User.
- No need to consider If the user has collection.

**Comment by paynejd** [comment]
This works correctly
