### ISSUE TITLE
Mapping / Repository Search / Search, select and add (to existing collection)

### ISSUE THREAD

**Issue by fatmau** [OpenConceptLab/oclapi#439]
As a user
I want to select and add any mapping to collection
So that I will select a collection and confirm the action.

**Dependency:**

- #438    

**Acceptance Scenario:**

| No  | Given  | When  | Then  |
| ------------- | ------------- | ------------- | ------------- |
| 1 | I list mappings in repository page | I select one or multiple results  | Add to Collection appears |
| 2 | Scenario No 1  | I click the dropdown | I see all my existing collections on the list  |
| 3 | Scenario No 2  | I select one of the user collection  | Save button returns actively clickable |
| 4 | Scenario No 3 | I click add button  | Confirmation box appears on the page. |
| 6 | Scenario No 5  | I click the Confirm button | I save the concepts |
| 7 | Scenario No 6  | I saved the concepts | I see approval box on the initial page |

**Mock-ups:**

- Mock-ups can be found at this URL --> https://marvelapp.com/---
- Check the link below to see the pages
https://drive.google.com/drive/u/0/folders/0B2RCqE113zNxNm9wdThQVXVvaEk

**Technical Assumptions:**

* This is for the Logged-in User.
* Organisation and personal collections should have different backgrounds.
* When the user refresh the page, it returns initial form.
* When the story is completed, selected mappings should be unselected.

**Comment by paynejd** [comment]
This is working correctly

**Comment by paynejd** [comment]
this works correctly
