### ISSUE TITLE
Mapping / Detail / Add to collection (without collection)

### ISSUE THREAD

**Issue by fatmau** [OpenConceptLab/oclapi#440]
As a user
I want to add my selected mapping to collection
So that I will see information when I do not have existing collection.

**Dependency:** 
-N/A

**Acceptance Scenario:**

| No  | Given  | When  | Then  |
| ------------- | ------------- | ------------- | ------------- |
| 1 | I see any mapping detail | I click 'Add to Collection' button | I list what I have in my collection |
| 2 | Scenario No 1  | I do not have existing collection | Information (create a collection in your profile) will be in the dropdown |
| 3 | Scenario No 2  | I click somewhere else beside dropdown | Page returns initial form |

**Mock-ups:**

- Mock-ups can be found at this URL --> https://marvelapp.com/---
-Check the link below to see the pages
https://drive.google.com/drive/u/0/folders/0B2RCqE113zNxNm9wdThQVXVvaEk

**Technical Assumptions:**

- This is for the Logged-in User.
- No need to consider If the user has collection.

**Comment by paynejd** [comment]
This is working correctly.
