### ISSUE TITLE
Mapping / Detail / Add to collection (to existing collection)

### ISSUE THREAD

**Issue by fatmau** [OpenConceptLab/oclapi#441]
As a user
I want to select and add any mapping to collection
So that I will select a collection and confirm the action.
**Dependency:**

- N/A 

**Acceptance Scenario:**

| No  | Given  | When  | Then  |
| ------------- | ------------- | ------------- | ------------- |
| 1 | I see any mapping detail | I click 'Add to Collection' button | I see all my existing collections on the list |
| 2 | Scenario No 1  | I select one of the user collection  | Save button returns actively clickable |
| 3 | Scenario No 2 | I click save button  | Info box appears on the page. |
| 4 | Scenario No 3  | Info box appears on the page | I click Confirm button and I add related mappings |
| 5 | Scenario No 4  | I saved the mappings | I see approval box on the initial page |

**Mock-ups:**

- Mock-ups can be found at this URL --> https://marvelapp.com/----
-Check the link below to see the pages
https://drive.google.com/drive/u/0/folders/0B2RCqE113zNxNm9wdThQVXVvaEk

**Technical Assumptions:**

- This is for the Logged-in User.
- Organisation and personal collections should have different backgrounds.
- When the user refresh the page, initial form.

**Comment by paynejd** [comment]
This all works correctly but I'd like to make a minor change to the confirmation text. Please update this window:

![image](https://cloud.githubusercontent.com/assets/1189689/24550816/cf6f5ae8-15ed-11e7-856c-e07dc3f861b8.png)

To say this:
`Added the latest version of this mapping to "collectionOwner / collectionName". Future updates to this resource will not be reflected automatically in the collection.`

... where collectionOwner and collectionName are replaced with the actual values, e.g. `paynejd / MyCollection`

**Comment by paynejd** [comment]
The "Add to Collection" dropdown only works on the "Details" tab -- it is always empty on the History tab.

![image](https://cloud.githubusercontent.com/assets/1189689/24550947/754e4a0a-15ee-11e7-9dec-06c9ac3a226c.png)
