### ISSUE TITLE
Concept / Add Single Ref / Add from mapping of concept

### ISSUE THREAD

**Issue by fatmau** [OpenConceptLab/oclapi#444]
As a user
I want to add a concept to any collection
So that API will add 'from' mapping of concept.

**Dependency:**

- #443 

**Acceptance Scenario:**
Collection Name: Test

| Concept Name | Mapping Name  | Mapping from  | Mapping to  |
| ------------- | ------------- | ------------- | ------------- | 
| X  | A  | X  | Y  |
| X  | B  | Y  | X  |

| No  | Given  | When  | Then  |
| ------------- | ------------- | ------------- | ------------- |
| 1 | ---- | I add concept called 'X' to collection called 'Test' via API or Add by URL page.   | I will see a pop-up which shows UI that Mapping A also will be added into collection Test |
| 2 | ---- | I click 'Close' button.   | Mapping A will be added into collection Test |
| 3 | ---- | Mapping A is in the collection Test.   | I will see a info box that both concept added to collection Test |

**Technical Assumptions:**

-Check the link below to see the pages
https://drive.google.com/drive/u/0/folders/0B2RCqE113zNxNm9wdThQVXVvaEk
- This story is all about API side.

**Comment by berkansahan** [comment]
' Related mappings of this concept will be added to your collection ' is written in the pop-up which we show as an information. Instead of this text message, we should rewrite **"Related mappings stored in the same source are also added to colletion.''**

**Comment by djazayeri** [comment]
The behavior works as is written in this story. However I do not want this behavior.
Automatically adding the mappings should happen for all the UI workflows _except_ for this one.
"Add by url" is the advanced case that should let you add just one thing at a time, without any automatic behaviors.

**Comment by berkansahan** [comment]
If we do not want this behaviour in especially ''Add by url'' page,  we should close this issue (because it is working now) and create a new task to implement not to add mappings automatically for this page. @djazayeri

**Comment by djazayeri** [comment]
With the combination of this story and #502 I approve of the behavior.
