### ISSUE TITLE
Concept / Add Multiple Ref / Add from mapping of concept

### ISSUE THREAD

**Issue by fatmau** [OpenConceptLab/oclapi#445]
As a user
I want to add a concept to any collection
So that API will add 'from' mappings of concept stored in the same source.

**Dependency:**

- #443 

**Acceptance Scenario:**
Collection Name: Test

| Concept Name | Mapping Name  | Mapping from  | Mapping to  |
| ------------- | ------------- | ------------- | ------------- | 
| X  | A  | X  | Y  |
| X  | B  | Y  | X  |
| | | | | 
| Q  | C  | Q  | Y  |
| Q  | D  | Y  | Q  |
| | | | |
| Z  | E  | T  | Y  |
| Z  | F  | Y  | T  |

| No  | Given  | When  | Then  |
| ------------- | ------------- | ------------- | ------------- |
| 1 | ---- | I add concept called 'X','Q' and 'Z' to collection called 'Test' via API or Add by Organisation or User.   | I will see a pop-up which wants me to confirm at UI that Mapping A also will be added into collection 'Test' |
| 2 | ---- | I click 'Close' button.   | Mapping A and C will be added into collection 'Test' |
| 3 | ---- | Mapping A and C are in the collection 'Test'.   | I will see a info box that both concept and mapping added to collection Test |

**Technical Assumptions:**

-Check the link below to see the pages
https://drive.google.com/drive/u/0/folders/0B2RCqE113zNxNm9wdThQVXVvaEk
- This story is mainly related with API side.

**Comment by berkansahan** [comment]
' Related mappings of this concept will be added to your collection ' is written in the pop-up which we show as an information. Instead of this text message, we should rewrite **"Related mappings stored in the same source are also added to colletion.''**

**Comment by djazayeri** [comment]
The popup looks like this:
![image](https://cloud.githubusercontent.com/assets/1165236/23573265/8ef6f8e2-0029-11e7-9c10-0fd723cdf57b.png)

I think the title should be "Added Related References"

The next label should say "We automatically added related mappings that are stored in the same source as the concept(s) you added to the collection." I would get rid of the yellow decoration and just it be normal text.

The list should show something more user-understandable than "/orgs/CIEL/sources/CIEL/mappings/58123c39613de50006d0fcbd/1/".

The first comment on this story says this should be a _confirmation_ popup, but it's actually implemented as an informational popup, and there's no option to cancel. I think that's good, but just wanted to point it out. (But I thought we wanted to add some informational text on https://staging.openconceptlab.org/users/djazayeri/collections/DxStart/references/new/ to inform people this behavior is going to happen.

**Comment by paynejd** [comment]
Quick feedback from conversation with Berkan:
* We want to consistently use the confirmation window in all locations where collections are added including the checkbox option to "automatically add associated mappings" when adding a concept reference
* Recommend changing "related mappings" to "associated mappings"
* Recommend adding a tooltip for "associated mapping" with a longer description: "A concept's **associated mappings** are mappings that originate from the specified concept (the 'from concept') and that are stored in the same source"

**Comment by berkansahan** [comment]
Here is the updated **Acceptance Scenario**

| No  | Given  | When  | Then  |
| ------------- | ------------- | ------------- | ------------- |
| 1 | ---- | I add concept called 'X','Q' and 'Z' to collection called 'Test' via API or Add by Organisation or User.   | I will see a pop-up which wants me to confirm at UI that Mapping A also will be added into collection 'Test' |
| 2 | ---- | I click 'Confirm' button.   | Mapping A and C will be added into collection 'Test' |
| 3 | ---- | Mapping A and C (stored in the same source) are in the collection 'Test'.   | I will see a info box that both concept and mapping added to collection Test |

-  'Automatically add associated mappings' checkbox will be selected.
- From mappings should be stored in the source to add automatically.
- This is for Logged-in User.

**Comment by djazayeri** [comment]
Functionally this works correctly.
Minor UX comment: the "Close" button should instead say "Cancel".
