### ISSUE TITLE
Concept / Global Search / Search, select and add (to existing collection) - Save

### ISSUE THREAD

**Issue by fatmau** [OpenConceptLab/oclapi#449]
As a user
I want to select and add any concept to collection
So that I will select a collection and cancel the action.
**Dependency:**

- #423  

**Acceptance Scenario:**

| No  | Given  | When  | Then  |
| ------------- | ------------- | ------------- | ------------- |
| 1 | I searched for concept with one or multiple result | I select one or multiple results  | Add to Collection appears |
| 2 | Scenario No 1  | I click the dropdown | I see all my existing collections on the list  |
| 3 | Scenario No 2  | I select one of the user collection  | Save button returns actively clickable |
| 4 | Scenario No 3 | I click save button  | Info box appears on the page. |
| 5 | Scenario No 4  | Info box appears on the page | I click Cancel button  |
| 6 | Scenario No 5  | I click the Cancel button | Page returns initial form  |

**Mock-ups:**

- Mock-ups can be found at this URL --> https://marvelapp.com/14d1eb3/screen/25642047
-Check the link below to see the pages
https://drive.google.com/drive/u/0/folders/0B2RCqE113zNxNm9wdThQVXVvaEk

**Technical Assumptions:**

- This is for the Logged-in User.
- Organisation and personal collections should have different backgrounds.
- No need to consider what is going to happen after 'Confirm' button has clicked.
- When the user refresh the page,it returns initial form.
- Code of yellow colour is: **#F8F0BF**

**Comment by djazayeri** [comment]
Small complaints:

* "Save" button in the popup would be clearer as "Add".
* "Close" button in the confirmation should be "Cancel"
* When I cancel, the state of the radio button and the checkbox are preserved. I would expect them to reset.

Otherwise this works great.

**Comment by paynejd** [comment]
This works correctly, but need to update success message slightly because it is only possible to add to a single collection at a time.

![image](https://cloud.githubusercontent.com/assets/1189689/24551491/aa809d02-15f0-11e7-88f4-f71d1b649514.png)
