### ISSUE TITLE
Source/Collection Atom Feeds are missing entries

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/oclapi#45]
Feeds are intended to enable tracking of all updates to concepts, not just to indicate whether a concept has been updated. Therefore, atom feeds for sources and collections should include the full feed for each concept that they contain, not only the latest update. It appears that currently the atom feed for sources/collections includes only a single update (the most recent) for each, which is less like a feed and more just a list of the most current versions for each concept.

**Comment by MisterNando** [comment]
@paynejd, I think I'll need a refresher on this one.  I don't recall the solution we agreed upon, nor do I understand my comment (above) on that solution.

**Comment by paynejd** [comment]
Based on how source versions and collections were implemented, it will not be possible to implement Atom feeds correctly at the source and collection levels without significant re-factoring, which we do not have time for.

The current implementation simply converts `GET /orgs/WHO/sources/ICD-10/latest/concepts/`into an RSS format. In other words, only one record per concept is returned. The correct implementation is that atom feeds contain a list of changes to concepts beginning with the most recent. Listing concept changes means that it must be pulling the data from concept versions.

Unfortunately we will have to delay this feature.
