### ISSUE TITLE
Concept / Global Search / Search, select and add (to existing collection) - Approve

### ISSUE THREAD

**Issue by fatmau** [OpenConceptLab/oclapi#450]
As a user
I want to select and add any concept to collection
So that I will select a collection and cancel the action.
**Dependency:**

- #423, #449  

**Acceptance Scenario:**

| No  | Given  | When  | Then  |
| ------------- | ------------- | ------------- | ------------- |
| 1 | I searched for concept with one or multiple result | I select one or multiple results  | Add to Collection appears |
| 2 | Scenario No 1  | I click the dropdown | I see all my existing collections on the list  |
| 3 | Scenario No 2  | I select one of the user collection  | Save button returns actively clickable |
| 4 | Scenario No 3 | I click save button  | Info box appears on the page. |
| 5 | Scenario No 4  | Info box appears on the page | I click Confirm button  |
| 6 | Scenario No 5  | I click the Save button | I see concept(s) and 'from' mapping(s) in the user collection |
| 7 | Scenario No 6  | I saved the concepts | I see approval box on the initial page |

**Mock-ups:**

- Mock-ups can be found at this URL --> https://marvelapp.com/14d1eb3/screen/25608673
-Check the link below to see the pages
https://drive.google.com/drive/u/0/folders/0B2RCqE113zNxNm9wdThQVXVvaEk

**Technical Assumptions:**

- This is for the Logged-in User.
- Organisation and personal collections should have different backgrounds.
- No need to consider what is going to happen after 'Confirm' button has clicked.
- When the user refresh the page, initial form.
-When the story is completed, selected concept do not become unselected.

**Comment by paynejd** [comment]
This all works correctly with one minor piece of feedback: If I "Cancel" out of the "Add to Collection" Confirmation Window, I want the checkboxes to stay checked. Currently they are automatically cleared.
