### ISSUE TITLE
mappings_url generated incorrectly for collections

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/oclapi#451]
In collections, the `mappings_url` field is generated incorrectly. It should follow the same pattern as the `concepts_url` field. See below for example:

```
https://www.openconceptlab.org/orgs/EthiopiaNHDD/collections/NCoD-Extended/?debug=1
```
```
{u'active_concepts': 0,
 u'active_mappings': 0,
 u'collection_type': u'Subset',
 u'concepts_url': u'/orgs/EthiopiaNHDD/sources/NCoD-Extended/concepts/',
 u'created_by': u'paynejd',
 u'created_on': u'2016-11-08T13:08:03.872',
 u'custom_validation_schema': None,
 u'default_locale': u'en',
 u'description': u'',
 u'external_id': u'',
 u'extras': None,
 u'full_name': u'National Classification of Diseases: Extended Edition',
 u'id': u'NCoD-Extended',
 u'mappings_url': u'/orgs/EthiopiaNHDD/sources/EthiopiaNHDD/concepts/NCoD-Extended/mappings/',
 u'name': u'National Classification of Diseases: Extended Edition',
 u'owner': u'EthiopiaNHDD',
 u'owner_type': u'Organization',
 u'owner_url': u'/orgs/EthiopiaNHDD/',
 u'public_access': u'View',
 u'references': [],
 u'short_code': u'NCoD-Extended',
 u'supported_locales': [u'en'],
 u'type': u'Collection',
 u'updated_by': u'paynejd',
 u'updated_on': u'2016-11-08T13:08:03.872',
 u'url': u'/orgs/EthiopiaNHDD/collections/NCoD-Extended/',
 u'uuid': u'5822148364d700001440f457',
 u'versions': 1,
 u'versions_url': u'/orgs/EthiopiaNHDD/collections/NCoD-Extended/versions/',
 u'website': u''}
```

**Comment by lnball** [comment]
@paynejd  - If I understand correctly, this seems fixed.  concepts_url and mappings_url have similar "pattern".

{u'active_concepts': 0,
 u'active_mappings': 2066,
 u'collection_type': u'Subset',
 u'concepts_url': u'/orgs/EthiopiaNHDD/collections/NCoD-Extended/concepts/',
...
 u'mappings_url': u'/orgs/EthiopiaNHDD/collections/NCoD-Extended/mappings/',

**Comment by djazayeri** [comment]
When I look at both https://staging.openconceptlab.org/orgs/EthiopiaNHDD/collections/NCoD-Extended/?debug=1 and https://www.openconceptlab.org/orgs/EthiopiaNHDD/collections/NCoD-Extended/?debug=1 the `mappings_url` field is not like what's shown in the first comment on this issue.

I also looked at a collection I created today (https://staging.openconceptlab.org/users/djazayeri/collections/483/?debug=1) and it seems like the mappings_url follows the right pattern.

I agree with @lnball that this seems to be fixed.
