### ISSUE TITLE
Mismatch between search result count, facet counts, and actual resource count

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/oclapi#457]
On staging, there is a mismatch between the search results count and the number of results shown in the filter/facets and the count of resources actually in the source. Take a look at https://staging.openconceptlab.org/orgs/EthiopiaNHDD/sources/ and notice that there are 851 concepts and 850 mappings -- these are the correct counts. Now, click on the EHAH source and go to the mappings tab. Notice that there are only 835 results in the count, however at left in the facets there are 850 results for many of these facets. Why/how is there a mismatch here? If I remember correctly, the search results count comes from the response header.

![image](https://cloud.githubusercontent.com/assets/1189689/22455134/a3d851bc-e79b-11e6-9745-ae3a2de4229c.png)

![image](https://cloud.githubusercontent.com/assets/1189689/22455142/b15f5cae-e79b-11e6-9af7-297b7b3366fb.png)

**Comment by molgun** [comment]
Hi Jon,

I suspect that this is a synchronisation issue between MongoDB and Solr. At the organisation page it fetches mapping count from MongoDB. But at Source page it fetches mapping count from Solr. 

I think we should *only* use MongoDB for write/read operations and use Solr only for searching. (I think searching is a discovery process not a read process). 

Now I ran update_index to sync MongoDB and Solr. Let's see if this is the issue.

**Comment by paynejd** [comment]
See comment on #454

**Comment by lnball** [comment]
@paynejd This seems to be correct (850 mappings are shown consistently on both pages).  I don't understand the sync between MongoDB and Solr.  Will this continue to be a problem?

**Comment by djazayeri** [comment]
(I can't UAT this now because https://staging.openconceptlab.org/orgs/EthiopiaNHDD/sources/EHAH/mappings/ is not showing any mappings. Maybe this is being reindexed.)

**Comment by paynejd** [comment]
It appears that this is still happening in several places. Take a look here: https://www.openconceptlab.org/orgs/EthiopiaNHDD/collections/

For every single one of these collections, the number of concept/mapping references listed does not match the number of concepts and mappings on those respective tabs
