### ISSUE TITLE
Collection detail's mappings_url and concepts_url fields are incorrect

### ISSUE THREAD

**Issue by heval** [OpenConceptLab/oclapi#469]
This is linked to #451 . Same description and reproduction steps. 
This one's about __concepts_url__ field

**Comment by djazayeri** [comment]
I can't UAT this because there's no hint at what I'm supposed to be testing.

**Comment by lnball** [comment]
@hevalberknevruz  Can you explain how to create this problem?  What are the symptoms?  Is this similar to #451?

**Comment by djazayeri** [comment]
The URL patterns look right to me.

https://staging.openconceptlab.org/users/djazayeri/collections/483/?debug=1 ...

*  u'concepts_url': u'/users/djazayeri/collections/483/concepts/'
*  u'mappings_url': u'/users/djazayeri/collections/483/mappings/'
*  u'owner_url': u'/users/djazayeri/'
*  u'versions_url': u'/users/djazayeri/collections/483/versions/'

@paynejd should probably confirm this, but I'm moving it to Done.
