### ISSUE TITLE
Rich Text Editor for About fields

### ISSUE THREAD

**Issue by djazayeri** [OpenConceptLab/oclapi#474]
### Background

We'd like to let content managers give better-structured, prettier descriptions of what their organizations, sources, collections, etc, are about. Currently the UI has various "About" tabs that are intended to show this content, but there's no way to edit it in the UI. We want to enable editing this field, and doing so with a rich text editor.

Since the users of this are not primarily developers, we should prefer a WYSIWYG editor.

### Acceptance Criteria

1. On an organization's About page (e.g. https://staging.openconceptlab.org/orgs/OCL/about/), there is an Edit icon (if the user has permission)
2. On a source's About page (e.g. https://staging.openconceptlab.org/users/djazayeri/sources/OMRS/about/) there is an Edit icon (if the user has permission)
3. On a collection's About page (e.g. https://staging.openconceptlab.org/users/djazayeri/collections/TEST/about/) there is an Edit icon (if the user has permission)
4. Clicking on an edit icon switches the screen to edit mode, with a rich text editor
5. Saving the content updates the resource in the database with rich text (encoded in the JSON)
6. All three of these screens display the rich text.

### Tech Notes

Here is an example of a rich text editor: http://mindmup.github.io/bootstrap-wysiwyg/.

Whatever we choose does not need to be especially fancy, but it should produce data in some standard format (markdown or html without lots of extra junk in it), and it should strip out anything unsafe (e.g. script tags).

### Scope

Personally I would also like to also combine Details and About onto a single tab, but we might want to create a separate issue for this. What do you think @paynejd ?

**Comment by paynejd** [comment]
The About pages are currently stored as "about" custom attributes. For internally significant custom attributes, we would like to move towards prepending them with double underscore, so please implement this using the "__about" attribute. This also has the benefit of not deleting the old about text until we're ready.

Yes, please combine the "About" and "Details" pages.

Finally, note that About pages currently allow HTML syntax, though as Darius said, any standard format such as markdown is fine. Agree that it must strip out anything unsafe.
