### ISSUE TITLE
Performance issues when adding many references to a collection

### ISSUE THREAD

**Issue by djazayeri** [OpenConceptLab/oclapi#481]
I'm running a script to populate an OCL collection with all the concepts and mappings that are currently distributed with the OpenMRS Reference Application (2316 references in total).

When I do a PUT to https://api.staging.openconceptlab.org/orgs/OpenMRS/collections/RA/references whose body contains the 2316 references, it hangs for a long time, and eventually returns with 504 Gateway Time-out.

However it seems that the server actually accepted the data and is processing it in the background. When I periodically refresh https://staging.openconceptlab.org/orgs/OpenMRS/collections/ the number of concepts and mappings for this collection continue to increment. Of course this is confusing to the end-user since If I go to https://staging.openconceptlab.org/orgs/OpenMRS/collections/RA/concepts/ then I don't see any concepts there (yet?).

Ideally if the PUT is actually being accepted, and background-processed, it should immediately return a 202 Accepted status.

Also, it is confusing if there's a disconnect between the counts on the org/collections page vs viewing the collection itself.

**Comment by rkorytkowski** [comment]
It is the same when you try to create a version of the RA collection. The server responds with Time-out, but after some time it is actually created. Surprisingly creating an export file for the version is much faster and completes within a minute.

**Comment by paynejd** [comment]
Anything that updates the index seems to be really slow, which is what
happens when you create a new repository version. Generating the export
only reads data which seems to be working fairly fast.
