### ISSUE TITLE
Related mappings are still added when adding concept to collection fails

### ISSUE THREAD

**Issue by burakince** [OpenConceptLab/oclapi#483]
While adding a concept to a collection, its related mapping are added to the collection regardless whether adding the concept fails due to validation or not.

__Steps to reproduce__
   * Create source S1 with Basic validation
   * Create collection C1 with OpenMRS validation
   * Create concept Concept1 with Fully Specified Name "Flu" in "en" locale under source S1
   * Create concept Concept2 with Fully Specified Name "Flu" in "en" locale under source S1
   * Create at least one more concept under source S1
   * Create a mapping M1 between Concept2 and any other concept under S1
   * Add Concept1 to collection C1
   * Add Concept2 to collection C1

__Expected Behavior__
   * Adding Concept2 should fail due to name uniqueness validation rule
   * M1 should not be added automatically to C1

**Comment by djazayeri** [comment]
I don't understand what this scenario is supposed to be, so I can't test it.

**Comment by emrah-b** [comment]
@djazayeri updated the description, sorry for the confusion earlier

**Comment by lnball** [comment]
@emrah-b I should know how to do this, but I got stuck on "Add Concept1 to collection C1" .  How do I do this?  And why isn't it more obvious?  I followed the recipe and created Org, Collection1, Source1, Concept1, Concept2, Extra concept, and Mapping1.

**Comment by djazayeri** [comment]
My first attempt to test this went wrong because of an unrelated UI defect. If you look at https://staging.openconceptlab.org/users/djazayeri/sources/BASIC/concepts/C1/ you will see that the concept name is shown as "name1" even though that's in the French locale, and the source's default locale is English. This is misleading.
@paynejd is this a known bug? Or should we create an issue for it?

**Comment by djazayeri** [comment]
This issue itself works as advertised. I'm moving it to Done, but it would be nice to know what to do about the unrelated UI defect mentioned in my previous comment.
