### ISSUE TITLE
Cascading Flag to API

### ISSUE THREAD

**Issue by berkansahan** [OpenConceptLab/oclapi#496]
As a user
I want to add a concept to any collection
So that API will add 'from' mapping of concept stored in the same source by cascading flag

**Dependency:**

- N/A

**Acceptance Scenario:**
Collection Name: Test

| Concept Name | Mapping Name  | Mapping from  | Mapping to  | Stored source  |
| ------------- | ------------- | ------------- | ------------- | ------------- | 
| X  | A  | X  | Y  | Q  |
| X  | B  | Y  | X  | Q  |
| Y  | -  | -  | -  | Q  |

| No  | Given  | When  | Then  |
| ------------- | ------------- | ------------- | ------------- |
| 1 | ---- | I add concept called 'X' to collection called 'Test' via API or add reference page and select cascade stored in the same souce   | I will see at UI that Mapping A also will be added into collection Test |
| 2 | ---- | I add concept called 'X' to collection called 'Test' via API or add reference page and do not select cascade stored in the same souce   | I will only see at UI that Concept X is in the collection Test |

**Technical Assumptions:**

- **collection/C1/reference
collection/C1/reference?cascade=none**

- **collection/C1/reference?cascade=sourcemappings**

- This story is all about API side.

**Comment by djazayeri** [comment]
@berkansahan said via chat: "you may test it via #427, #429 or #450"

**Comment by djazayeri** [comment]
Since at least the happy path of #427 and #429 are working correctly, I infer the API must be working right, so I will mark this Done.
