### ISSUE TITLE
Concept / Add Single Ref / Do not Add from mapping of concept automatically

### ISSUE THREAD

**Issue by berkansahan** [OpenConceptLab/oclapi#502]
As a user
I want to add a concept to any collection
So that API will not add 'from' mapping of concept automatically.

**Dependency:**

N/A

**Acceptance Scenario:**
Collection Name: Test

| Concept Name | Mapping Name  | Mapping from  | Mapping to  |
| ------------- | ------------- | ------------- | ------------- | 
| X  | A  | X  | Y  |
| X  | B  | Y  | X  |

| No  | Given  | When  | Then  |
| ------------- | ------------- | ------------- | ------------- |
| 1 | ---- | I add concept called 'X' to collection called 'Test' via API or Add by URL page.   | Only concept X will be in my collection. Mappings will not be added automatically |

**Technical Assumptions:**

- This is for Logged-in User

**Comment by djazayeri** [comment]
I tested this on staging and it did not work as advertised. I added one concept using the Add By URL workflow, and it also added 4 mappings to the collection: https://staging.openconceptlab.org/users/djazayeri/collections/502/references/

**Comment by berkansahan** [comment]
It was not updated on staging, that's why it did not work. You may test it now.  @djazayeri

**Comment by djazayeri** [comment]
I tested again and it worked. Thanks!
