### ISSUE TITLE
Import script for mappings integrated into the concept import

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/oclapi#54]
Need a method for importing mappings. The approach will be defined when the new mappings model is defined.

**Comment by MisterNando** [comment]
Estimates:

Original - 2h
Updated - 2h

**Comment by MisterNando** [comment]
Mappings don't have a "code" to serve as a stable identifier, so I'm using external_id instead.  In other words, mappings are _required_ to have an external_id in order to be imported.  (Otherwise, we have no way to correlate them with mappings that are already in the system.)

Is there a better approach?

**Comment by paynejd** [comment]
Hi Aaron, for mappings identity is determined by checking if the same
relationship already exists (i.e. identical from_concept, to_concept, and
map_type) in the same source. If necessary, seems like it would be
straightforward to automatically create that ID as a field which may be
easier than calculating on the spot? Not sure if that is necessary though.

**Comment by MisterNando** [comment]
Usage:

```
./manage.py import_mappings_to_source --source=[source_uuid] --token=[token] [filename]
```

**Comment by pkshiu** [comment]
What is the format of the json input? Is it exactly as documented here?

https://github.com/OpenConceptLab/oclapi/wiki/mappings#create-a-new-mapping

Thx

**Comment by paynejd** [comment]
Aaron, we need some type of documentation with examples for how to do the modified concept/mapping import otherwise this isn't usable. Can you either direct us to the documentation (if you've already done it) or modify the https://github.com/OpenConceptLab/oclapi/wiki/Concept-Import page?

**Comment by MisterNando** [comment]
Added a section to the end of https://github.com/OpenConceptLab/oclapi/wiki/Concept-Import.

**Comment by pkshiu** [comment]
I imported just six mappings into dev. These are silly mappings from the actual CIEL source, which seems to create a "same-as" mapping for each mapping. i.e. mapping id 1 to id 1. Nevertheless, the imports were successful according to the import tool. I see new entries in mongo. But the mappings call are not returning anything.

See ~/map10.json for the input

Use this to query the API:

http://api.dev.openconceptlab.com/orgs/CIELTEST/sources/CIELTEST/concepts/1/mappings/

The import command I ran is:

./manage.py import_mappings_to_source --source=54e74b378a86f251d2e737d8 --token=22f6bf9500958d9a49b4a7c16203c17de3b59d45 ~/map10.json

**Comment by pkshiu** [comment]
@paynejd I am moving my external ID question here:

Do I treat the currently external mapping destination as external mappings?

For example, just take the first concept:

http://www.maternalconceptlab.com/search.php?q=id%3A1&source=openmrs


What would be the imported URL for the mappings? All I have is the source name, e.g.
"SNOMED CT” , “ICD-10-WHO” etc. Can I assume org name? e.g.

{
    "map_type": "SAME-AS",
    "to_concept_url": "/orgs/SNOMED-CT/sources/SNOMED-CT/concepts/413532003/",
    "from_concept_url": "/orgs/CIEL/sources/CIELTEST/concepts/1/"
}
{
    "map_type": "NARROWER-THAN",
    "to_concept_url": "/orgs/ICD-10-WHO/sources/ICD-10-WHO/concepts/D62/",
    "from_concept_url": "/orgs/CIEL/sources/CIELTEST/concepts/1/"
}

or 


{
    "map_type": "SAME-AS",
    "to_concept_code": "413532003",
   "to_source_code": "SNOMED-CT",
    "from_concept_url": "/orgs/CIEL/sources/CIELTEST/concepts/1/"
}
{
    "map_type": "NARROWER-THAN",
    "to_concept_code": "D62",
   "to_source_code": "ICD-10-WHO",
    "from_concept_url": "/orgs/CIEL/sources/CIELTEST/concepts/1/"
}

**Comment by MisterNando** [comment]
What was the output from the import command?

**Comment by pkshiu** [comment]
@MisterNando Next I am trying to import external mappings using the to_concept_code, to_source_code json format (see comment above):

```
./manage.py import_mappings_to_source --source=54e74b378a86f251d2e737d8 --token=22f6bf9500958d9a49b4a7c16203c17de3b59d45 ~/map_ext.json

Adding/updating 1 new mappings...
AttributeError: 'NoneType' object has no attribute 'id'
```

And I get the attributeError above.

**Comment by paynejd** [comment]
Hi PK,

As per the mappings spec on the wiki, this is the expected syntax to create external mappings (map_type, from_concept_url, to_source_url, and to_concept_code are required; to_concept_name is optional but recommended):

```
{
    "map_type": "Narrower Than",
    "from_concept_url": "/orgs/Columbia/sources/CIEL/concepts/116125/",
    "to_source_url": "/orgs/WHO/sources/ICPC-2/",
    "to_concept_code": "A73",
    "to_concept_name": "Malaria"
}
```

Please give this a try.

**Comment by pkshiu** [comment]
@paynejd note that the example json and the text description above it are not consistent. the text says "to_source_code" and the json example says "to_source_url".

Anyway a separate issue is that the external sources still need to be in the database so I am going to see if I can write a simple tool to create those first.

**Comment by paynejd** [comment]
Hi PK, thanks for catching the error in the wiki spec- I just went through
and fixed it. I believe that Aaron has implemented it according to the
JSON. Here is the corrected spec for creating external mappings:


   - *map_type* (required) string - map type
   - *external_id* (optional) string - external unique identifier for
   import/export
   - *from_concept_url* (required) string - relative URL of the "from"
   concept
   - *to_source_url* (required) string - relative URL of the "to" source
   (must be stored in OCL)
   - *to_concept_code* (required) string - code for the external to_concept
   - *to_concept_name* (optional) string - name of the external to_concept


{
    "map_type": "Narrower Than",
    "from_concept_url": "/orgs/Columbia/sources/CIEL/concepts/116125/",
    "to_source_url": "/orgs/WHO/sources/ICPC-2/",
    "to_concept_code": "A73",
    "to_concept_name": "Malaria"
}


--
Jonathan Payne, MS
615.579.5413
*LinkedIn:* www.linkedin.com/in/jonathandavidpayne
*Skype:* jonathandavidpayne

**Comment by paynejd** [comment]
Hi both, I did testing on creating new mappings and I am only able to create mappings under one situation that I tested: Creating an internal mapping when both of the concepts are in the same source as the new mapping. All other possible combinations that I tested failed, including the external mappings, which is probably why the mapping import hasn't been working. I tested each of these as "sysadmin2". Here were the results:

## Internal - mapping and concepts all in same source - SUCCESS!
* type: internal
* mapping source: `/user/sysadmin2/sources/MySource/`
* from_concept: `/user/sysadmin2/sources/MySource/concepts/1/`
* to_concept: `/user/sysadmin2/sources/MySource/concepts/2/`
* result: 201 CREATED

```JSON
POST /users/sysadmin2/sources/MySource/mappings/
{
    "map_type": "Colocated With",
    "from_concept_url": "/users/sysadmin2/sources/MySource/concepts/1/",
    "to_concept_url": "/users/sysadmin2/sources/MySource/concepts/2/"
}
```

```JSON
201 CREATED
{
    "type": "Mapping",
    "id": "54fb13e08a86f208ab906d00",
    "external_id": null,
    "retired": false,
    "map_type": "Colocated With",
    "from_source_owner": "sysadmin2",
    "from_source_owner_type": "User",
    "from_source_name": "MySource",
    "from_source_url": "/users/sysadmin2/sources/MySource/",
    "from_concept_code": "1",
    "from_concept_name": "Arm",
    "from_concept_url": "/users/sysadmin2/sources/MySource/concepts/1/",
    "to_source_owner": "sysadmin2",
    "to_source_owner_type": "User",
    "to_source_name": "MySource",
    "to_source_url": "/users/sysadmin2/sources/MySource/",
    "to_concept_code": "2",
    "to_concept_name": "Leg",
    "to_concept_url": "/users/sysadmin2/sources/MySource/concepts/2/",
    "source": "MySource",
    "owner": "sysadmin2",
    "owner_type": "User",
    "url": "/users/sysadmin2/sources/MySource/mappings/54fb13e08a86f208ab906d00/",
    "extras": null,
    "created_at": "2015-03-07T10:06:08.393",
    "updated_at": "2015-03-07T10:06:09.228",
    "created_by": "sysadmin2",
    "updated_by": "sysadmin2"
}
```


## Internal - mapping saved to different source than the concepts are in - FAILED
* type: Internal
* mapping source: `/user/sysadmin2/sources/MySource2/`
* from_concept: `/user/sysadmin2/sources/MySource/concepts/1/`
* to_concept: `/user/sysadmin2/sources/MySource/concepts/2/`
* result: 403 FORBIDDEN

```JSON
POST /users/sysadmin2/sources/MySource2/mappings/
{
    "map_type": "Colocated With",
    "from_concept_url": "/users/sysadmin2/sources/MySource/concepts/1/",
    "to_concept_url": "/users/sysadmin2/sources/MySource/concepts/2/"
}
```

```JSON
403 FORBIDDEN
{
    "detail": "You do not have permission to perform this action."
}
```


## Internal - mapping and from_concept same source, to_concept different source - FAILED
* type: Internal
* mapping source: `/user/sysadmin2/sources/MySource/`
* from_concept: `/user/sysadmin2/sources/MySource/concepts/1/`
* to_concept: `/orgs/CIELTEST/sources/CIELTEST/concepts/999/`
* result: 400 BAD REQUEST

```JSON
POST /users/sysadmin2/sources/MySource/mappings/
{
    "map_type": "Related to",
    "from_concept_url": "/users/sysadmin2/sources/MySource/concepts/1/",
    "to_concept_url": "/orgs/CIELTEST/sources/CIELTEST/concepts/999/"
}
```

```JSON
400 BAD REQUEST
{
    "to_concept_url": [""]
}
```


## External - mapping and from_concept from same source, to_concept external
* type: External
* mapping source: `/user/sysadmin2/sources/MySource/`
* from_concept: `/users/sysadmin2/sources/MySource/concepts/1/`
* to_source: `/users/sysadmin2/sources/MySource2/`
* to_concept_code: 1a
* to_concept_name: Tibia
* result: 400 BAD REQUEST

```
POST /users/sysadmin2/sources/MySource/mappings/
{
    "map_type": "Narrower Than",
    "from_concept_url": "/users/sysadmin2/sources/MySource/concepts/1/",
    "to_source_url": "/users/sysadmin2/sources/MySource2/",
    "to_concept_code": "1a",
    "to_concept_name": "Tibia"
}
```

```
400 Bad Request
{
    "to_source_url": [""]
}
```


## External - mapping saved different source than the from_concept, to_concept external
* type: External
* mapping source: `/user/sysadmin2/sources/MySource/`
* from_concept: `/orgs/CIELTEST/sources/CIELTEST/concepts/999/`
* to_source: `/orgs/CIELTEST/sources/CIELTEST2/`
* to_concept_code: 1a
* to_concept_name: Tibia
* result: 400 BAD REQUEST

```
POST /users/sysadmin2/sources/MySource/mappings/
{
    "map_type": "Narrower Than",
    "from_concept_url": "/orgs/CIELTEST/sources/CIELTEST/concepts/999/",
    "to_source_url": "/orgs/CIELTEST/sources/CIELTEST2/",
    "to_concept_code": "1a",
    "to_concept_name": "Tibia"
}
```

```
400 Bad Request
{
    "to_source_url": [""], 
    "from_concept_url": [""]
}
```

**Comment by pkshiu** [comment]
New problem with importing. I fixed the import inputs, as well as loaded external orgs and sources into dev. Now:

```
./ocl/manage.py import_mappings_to_source --source=54e74b378a86f251d2e737d8 --token=22f6bf9500958d9a49b4a7c16203c17de3b59d45 ~/map_ext.json
Adding/updating 163 new mappings...
AttributeError: 'MappingsImporter' object has no attribute 'limit'
```

The map_ext.json file contains mappings from the first 50 concepts in the ciel database.

**Comment by MisterNando** [comment]
@pkshiu , there were some bugs in the importer, but there's also bad input in the JSON file.  Some of the lines aren't valid JSON; most of the others are missing a 'to_concept_name':

```
Could not persist new mapping due to {'__all__': [u"Must specify either 'to_concept' or 'to_source', 'to_concept_code' & 'to_concept_name'"]}

Failed to parse line {u'map_type': u'SAME-AS', u'to_concept_code': u'37226', u'to_source_url': u'/orgs/IMO/sources/IMO-ProblemIT/', u'from_concept_url': u'/orgs/CIELTEST/sources/CIELTEST/concepts/50/'}.  Skipping it...
```

**Comment by paynejd** [comment]
Not sure if I'm reading this correctly, but just to make sure we are all on
the same page:

For internal maps, three fields are required:

   - map_type
   - from_concept_url
   - to_concept_url

For external maps, 4 fields are required and "to_concept_name" is optional:

   - map_type
   - from_concept_url
   - to_source_url
   - to_concept_code



--
Jonathan Payne, MS
615.579.5413
*LinkedIn:* www.linkedin.com/in/jonathandavidpayne
*Skype:* jonathandavidpayne

**Comment by MisterNando** [comment]
Okay, that's not how it's implemented.  I'll make "to_concept_name" a non-required field.

**Comment by pkshiu** [comment]
@MisterNando is this fixed? I still cannot import it (using the same file mentioned above). I still get:

Could not persist new mapping due to {'__all__': [u"Must specify either 'to_concept' or 'to_source', 'to_concept_code' & 'to_concept_name'"]}

Failed to parse line {u'map_type': u'SAME-AS', u'to_concept_code': u'37226', u'to_source_url': u'/orgs/IMO/sources/IMO-ProblemIT/', u'from_concept_url': u'/orgs/CIELTEST/sources/CIELTEST/concepts/50/'}.  Skipping it...

Can you make sure you can run the import? 
You mentioned the json is invalid? I created it via the json.dumps() util. And I can load it back as well. If it is invalid can you tell me which part?

Thx.

**Comment by MisterNando** [comment]
I can't reproduce all these failure cases.  For example:

## Internal - mapping saved to different source than the concepts are in - FAILED

**Comment by pkshiu** [comment]
Can you run my import file and make sure that works? That will give me a positive case to figure out the others.
Thanks,
-- PK

**Comment by MisterNando** [comment]
It ran successfully! ...almost.  In 20 instances, it failed due to:

```Could not persist new mapping due to {'__all__': [u'Cannot map concept to itself.']}```

But the other 137 succeeded.  After that, I rebuilt the Solr index, and now you can see all the mappings at: http://api.dev.openconceptlab.com/mappings/.

Optimistically marking this "Closed".

**Comment by paynejd** [comment]
Awesome! I'm testing now...

@pkshiu FYI that the CIEL maps should not be implemented -- they will all
result in mapping a concept to itself. These were a hack that CIEL used
that the OCL Subscription module addresses.

--
Jonathan Payne, MS
615.579.5413
*LinkedIn:* www.linkedin.com/in/jonathandavidpayne
*Skype:* jonathandavidpayne

**Comment by pkshiu** [comment]
Will fix and reload a lot more tonight

**Comment by paynejd** [comment]
Please add in the "external_id" for maps as well.

--
Jonathan Payne, MS
615.579.5413
*LinkedIn:* www.linkedin.com/in/jonathandavidpayne
*Skype:* jonathandavidpayne
