### ISSUE TITLE
change log file at /var/log/solr/... to rotating 

### ISSUE THREAD

**Issue by pkshiu** [OpenConceptLab/oclapi#58]
As soon as I find out where that is configured !

**Comment by MisterNando** [comment]
Estimate: 2h

**Comment by paynejd** [comment]
Aaron, can you indicate where this file lives (if you know)? PK will take care of this one.

**Comment by MisterNando** [comment]
Looks like the command that runs solr is:

```
usr/bin/java -Dsolr.solr.home=/opt/deploy/solr -Djetty.logs=/var/log/solr -Djetty.home=/opt/solr -Djava.io.tmpdir=/tmp -jar /opt/solr/start.jar --daemon
```

This is generated by:
```
/etc/init.d/jetty
```

Which pulls in:
```
/etc/default/jetty
```

Which specifies the log location:
```
JAVA_HOME=/usr/lib/jvm/jre-1.7.0-openjdk
JAVA_OPTIONS="-Dsolr.solr.home=/opt/deploy/solr $JAVA_OPTIONS"
JETTY_HOME=/opt/solr
JETTY_USER=deploy
# Centralize logs to /var/log
# JETTY_LOGS=/opt/solr/logs
JETTY_LOGS=/var/log/solr
```

**Comment by pkshiu** [comment]
Hey guys sorry I have been out of commission for a bit, this "issue" is we need to figure out how to change the logger config for JETTY

**Comment by MisterNando** [comment]
I don't know how to do that offhand, but if it's easier to do in another application container, there's really no compelling reason to stick with Jetty.

**Comment by paynejd** [comment]
@pkshiu  Is this complete?
