### ISSUE TITLE
Verbose concept search returns retired flag wrong

### ISSUE THREAD

**Issue by pkshiu** [OpenConceptLab/oclapi#61]
If given such a request:

/v1/concepts/?q=ANEMIA&limit=25&page=5&verbose=true

the "retired" flag is always returned false.

The bug is either (or both):

- retired concepts should not be returned
- retired concepts should have "retired" returned true

Not confirmed, but it is possible that this also occurs for concept searches within sources/collections.

e.g. in dev environment"
```
http://localhost:8000/search/?q=ANEMIA&page=5
```
look for concept ID 3 near the end. This concept is retired, but it is returned from the searched, and the code that "strikes out" the concept name does not fire because the concept.retired is false.

If you click into the detail view 
```
http://localhost:8000/orgs/OMRS/sources/OMRS/concepts/3/
```
you will see that the retired flag is correctly set and the display (at the breadcrumb) correctly stirkes out the name.

**Comment by MisterNando** [comment]
Estimate: 2h

**Comment by MisterNando** [comment]
I am unable to reproduce this one as well.  The query noted (with the limit parameter adjusted to return all):

http://api.dev.openconceptlab.com/v1/concepts/?q=ANEMIA&verbose=true

yields 126; none of which have retired=true.  However, 

http://api.dev.openconceptlab.com/v1/concepts/?q=ANEMIA&verbose=true&include_retired=true

yields 129; 3 of which have retired=true.

**Comment by MisterNando** [comment]
Repeated this experiment this morning with the correct includeRetired parameter; observed same result.

**Comment by pkshiu** [comment]
I will reload dev data later tonight and try to retire some concepts to test, is that ok @MisterNando @paynejd ?

**Comment by MisterNando** [comment]
Works for me!

**Comment by MisterNando** [comment]
Blocked on #93.
