### ISSUE TITLE
home / global concept counts is off, possibly includes retired concept

### ISSUE THREAD

**Issue by pkshiu** [OpenConceptLab/oclapi#62]
This issue maybe related to #61 , the count in the left corner is larger than summing up the concept counts when looking at sources directly. Note that the top-right box uses HEAD while the actual search uses GET. The presence of "retired" concepts is definitely influencing the numbers some, so probably fix the "includeRetired" issue first, then fix this. 

Here's an example:

```
http://localhost:8000/search/
# vs
http://localhost:8000/search/?type=sources
```

![screen shot 2015-01-10 at 8 28 02 pm](https://cloud.githubusercontent.com/assets/131852/5693981/8a4f0874-9907-11e4-92f1-74388057724d.png)

**Comment by MisterNando** [comment]
Estimate: 2h

**Comment by MisterNando** [comment]
@pkshiu , which calls are you making to the API (and which verbs) that are yielding inconsistent results?

**Comment by paynejd** [comment]
Its a HEAD vs. GET request. One possibility is that the HEAD request is
using different parameters. I'll let PK respond with the details.

**Comment by pkshiu** [comment]
Like @paynejd said, it's a simple HEAD of "concepts", "users" etc

BTW so there is a separate bug (once we fixed this one) on the web site that currently the HEAD requests do not pass any query parameters. But the counts are wrong for the q=nothing case anyway, right?

**Comment by MisterNando** [comment]
I'm seeing no discrepancies on dev or on staging :-/

**Comment by MisterNando** [comment]
@pkshiu , the count is probably including the "partially retired" concepts, as you suggested.  Please refresh dev with a smaller set of data, so we can try again.  Thanks!

**Comment by MisterNando** [comment]
Blocked on #93.

**Comment by MisterNando** [comment]
@pkshiu , I don't think it's counting retired concepts any more - I retired a concept and verified that the total count decreased by 1.

However, now I'm seeing the opposite problem to what you described - the number of concepts for one source exceeds the total number of concepts.  This isn't problematic in and of itself, but when I retired the concept, _that_ count didn't decrease.  Is that by design?

**Comment by pkshiu** [comment]
@MisterNando I think all the counts on the website I just get from the HEAD calls to the API. So any issues should be from the API side?

**Comment by MisterNando** [comment]
Verified that GET and HEAD are returning the same counts in the header for all of the following:

http://api.dev.openconceptlab.com/concepts/
http://api.dev.openconceptlab.com/concepts/?includeRetired
http://api.dev.openconceptlab.com/orgs/CIELTEST/sources/CIELTEST/concepts/
http://api.dev.openconceptlab.com/orgs/CIELTEST/sources/CIELTEST/concepts/?includeRetired

**Comment by paynejd** [comment]
Using the token for "sysadmin2" on dev, I tried all 4 of the above links using both GET and HEAD. The first 2 worked perfectly fine. The second 2 both worked fine using GET but returned `403 FORBIDDEN` using HEAD.

![image](https://cloud.githubusercontent.com/assets/1189689/6407227/fd2f7fe6-be09-11e4-8cc6-ea9b4e90c0fc.png)

![image](https://cloud.githubusercontent.com/assets/1189689/6407232/0954259c-be0a-11e4-8bcd-db566de3ccc7.png)
