### ISSUE TITLE
updatedSince parameter fails to filter concept results

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/oclapi#67]
Applying the "updatedSince" parameter (e.g. updatedSince=2015-01-08T19:34:16Z) fails to filter out concepts updated before the specified datetime.

Example:

http://api.staging.openconceptlab.com/v1/orgs/COLUMBIA/sources/CIEL/concepts/?verbose=true&include_retired=true&limit=100&updatedSince=2015-01-08T19:34:16Z

**Comment by MisterNando** [comment]
Estimate: 2h

**Comment by MisterNando** [comment]
I think this was just a matter of camel case vs. roadkill case.  This should be fixed in the next deploy.

**Comment by MisterNando** [comment]
It was not a matter of case, but I found the root cause.  Will be fixed in the next deploy.
