### ISSUE TITLE
All concept searches should NOT include retired concepts unless "includeRetired" parameter is set to true

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/oclapi#69]
As indicated in the specs, retired concepts should not be included in any of the concept search results unless the "includeRetired" parameter is set to true. Right now, there is no way to exclude retired concepts from the search results.

**Comment by MisterNando** [comment]
Estimate: 2h

**Comment by MisterNando** [comment]
Again, I think this is a matter of camel case vs. roadkill.

**Comment by MisterNando** [comment]
This is now working properly on dev.
