### ISSUE TITLE
Provide API-level traffic statistics tracked by user

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/oclapi#73]
For example, which CRUD action took place on which resource by what user? Big plus if stats can be made available to the Web UI for an administrative user.

Capture timestamp, username, request URL, IP address, response code, resource ID
Store this info somewhere away from log files

**Comment by MisterNando** [comment]
Estimates:

Original - 4h
Updated - 6h

**Comment by GauravButola** [comment]
We've added request/response logs in the API which shows the user who made the request, their IP, time it took for the server to respond, request method, URL, and response code.
<img width="733" alt="screen shot 2016-09-27 at 12 41 04 pm" src="https://cloud.githubusercontent.com/assets/734636/18863733/8a4054c8-84b0-11e6-83bc-366e25e77727.png">

We've not yet made the logs available through a Web UI, instead it's saved as a regular log file.
