### ISSUE TITLE
Remove the "concept version" dependency that mappings currently have

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/oclapi#74]
Currently, when a create, update, or delete operation is performed on a mapping, a new version of the "from_concept" is automatically created noting the change. This enhancement will completely remove the "concept version" dependency between mappings and concepts.

Originally estimated at 0 hours of work.

**Comment by MisterNando** [comment]
Estimates:

Original - 0h
Updated - 0h

(Part of #77)
