### ISSUE TITLE
Add "external_uuid" as an optional core attribute of concepts, names, descriptions, concept extras, and mappings

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/oclapi#75]
The "external_uuid" will be used during import/export so that OCL can maintain its own UUIDs but still retain an external sources UUIDs upon import.

Originally estimated at 2 hours of work.

**Comment by MisterNando** [comment]
Estimates:

Original - 0h
Updated - 0h

(Part of #77)

**Comment by MisterNando** [comment]
Estimates:

Original - 2h
Updated - 2h

**Comment by MisterNando** [comment]
@paynejd , working on this now

**Comment by paynejd** [comment]
Hi Aaron, I forgot to change the title to indicate that we were going to
add external_id to source and collection as well, even though I already
added to spec. Not sure if you already did it but if not and its a quick
fix would be great to have it.
