### ISSUE TITLE
Modify/create new Solr index to support the new mappings implementation

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/oclapi#76]
1. Search concepts using map codes (this is the same thing as the way that you can use concept names/descriptions to search for concepts) - e.g. searching for "A15.1" should pull up the actual ICD-10 A15.1 concept first, if it exists (since a matching ID should be highly weighted) then also also show any concepts that are mapped to A15.1 next (regardless of whether A15.1 is an internal or external mapping)
2. Mappings must be searchable via an index at the top-level (/mappings), within sources (e.g. `/orgs/[org]/sources/[source]/mappings`), and within source versions (e.g. `/orgs/[org]/sources/[source]/[version]/mappings`)
3. Both of the above should be able to be filtered by map_type

Originally estimated 8 hours of work to complete.

**Comment by MisterNando** [comment]
Estimates:

Original - 8h
Updated - 4h
