### ISSUE TITLE
Lucene query syntax (e.g. boolean logic) should be supported for all search queries and filters

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/oclapi#79]
Currently, it is not possible to use any of the standard Lucene query language when searching resources or applying filters. This means that currently only one search term or filter can be sent at a time. For example, it is not possible to filter concepts using Datatype = "Anatomy OR Diagnosis". As much as possible, the Lucene query language should be supported at the API level for search criteria and for filters. The full Lucene query syntax is here: http://lucene.apache.org/core/2_9_4/queryparsersyntax.html

The API should support passing these values as text parameters **in the same syntax as Lucene syntax**. The table below lists which modifiers are currently supported and which are required. Ideally, all will be supported, but the priority is on those listed as "required" features.

| Lucene Search Operator | Example | Currently Supported by API | Required Feature by API |
| -------------- | ----- | ------- | ------- |
| Terms | `malaria pregnancy` | YES | YES |
| Boolean Operators | `"jakarta apache" jakarta`, `"jakarta apache" OR jakarta`, `"jakarta apache" AND "Apache Lucene"`, `+jakarta lucene`, `"jakarta apache" NOT "Apache Lucene"`, `"jakarta apache" -"Apache Lucene"` | NO | YES |
| Fields | `title:"The Right Way"`, `text:go` | NO | YES |
| Wildcard Search | `chil?`, `chil*`, `te*t` | NO | YES |
| Escaping Special Characters | `\(1\+1\)\:2` | NO | YES |
| Fuzzy Search | `roam~`, `roam~0.8` | NO | NO |
| Proximity Search | `"jakarta apache"~10` | NO | NO |
| Range Search | `mod_date:[20020101 TO 20030101]`, `title:{Aida TO Carmen}` | NO | NO |
| Term Boosting | `jakarta^4 apache` | NO | NO |
| Grouping | `(jakarta OR apache) AND website` | NO | NO |

**Comment by MisterNando** [comment]
Estimate: 3h

**Comment by MisterNando** [comment]
@paynejd , I implemented this and pushed it to dev.  However, there are 2 caveats:

1. I would assert that the API client shouldn't know anything about the naming of Solr fields, and therefore field search should not be allowed.  (We have a separate mechanism for specifying filters and facets.)

2. We can support escaping of special characters, but I'm not sure if this buys us anything.  When the index is created, non-alphanumeric characters are treated as token-boundaries and are ignored.

The other operators you specified as NOT required are actually pretty cheap to support, so I've included them as well (with the exception of range search, for the same reason as caveat #1 above).

If this is acceptable, please close the ticket.

**Comment by paynejd** [comment]
I have not tested this yet, but your approach makes sense to me. I will test tomorrow and close.

Can you please confirm that it is possible to pass more than one filter/facet of the same type? e.g. What is the syntax to apply datatype = "Anatomy OR Diagnosis"?

**Comment by paynejd** [comment]
The following functionality was implemented:

| Lucene Search Operator | Example | Implemented |
| -------------- | ----- | ------- | ------- |
| Terms | `malaria pregnancy` | YES |
| Boolean Operators | `"jakarta apache" jakarta`, `"jakarta apache" OR jakarta`, `"jakarta apache" AND "Apache Lucene"`, `+jakarta lucene`, `"jakarta apache" NOT "Apache Lucene"`, `"jakarta apache" -"Apache Lucene"` | YES |
| Fields | `title:"The Right Way"`, `text:go` | NO - Use filters/facets |
| Wildcard Search | `chil?`, `chil*`, `te*t` | YES |
| Escaping Special Characters | `\(1\+1\)\:2` | NO - Solr removes special chars in index |
| Fuzzy Search | `roam~`, `roam~0.8` | YES |
| Proximity Search | `"jakarta apache"~10` | YES |
| Range Search | `mod_date:[20020101 TO 20030101]`, `title:{Aida TO Carmen}` | NO - Use filters/facets |
| Term Boosting | `jakarta^4 apache` | YES |
| Grouping | `(jakarta OR apache) AND website` | YES |

**Comment by paynejd** [comment]
Reopening until this functionality is confirmed:

How do you pass more than one filter/facet of the same type to the API? e.g. What is the syntax to apply datatype = "Anatomy OR Diagnosis"?

**Comment by MisterNando** [comment]
That's a tricky one.  As I see it, you have two options here:
1. Allow the filter value to be a comma-separated list of tokens, and "OR" them together on the backend (e.g. datatype=Anatomy,Diagnosis).
2. Include the filter fields in the generic text search.

Or we could just disallow it.  Is there a compelling use case for this feature?

**Comment by paynejd** [comment]
#1 is the best option -- it will allow users to check options from a list
to filter search results, like selecting airlines on kayak. We already show
the facet options on the global search but they can only select one at a
time. Thus functionality is what will make facets  useful.

**Comment by MisterNando** [comment]
Implemented Option 1.
