### ISSUE TITLE
includeReverseMapping does not work with concept details query

### ISSUE THREAD

**Issue by pkshiu** [OpenConceptLab/oclapi#80]
The "includeInverseMappings" options does not return inverse mappings for a concept.

For example, *Rash* (ID 512) is a question mapped to answer *yes* (ID 1065).

The reverse query for 1065 does not returns 512 in dev.

```
http://api.dev.openconceptlab.com//v1/orgs/OMRS/sources/OMRS/concepts/512/mappings/?includeInverseMappings=True
http://api.dev.openconceptlab.com//v1/orgs/OMRS/sources/OMRS/concepts/1065/mappings/?includeInverseMappings=true

# for reference:
http://www.maternalconceptlab.com/search.php?q=id:512&source=openmrs
```

**Comment by MisterNando** [comment]
Estimate: 2h

**Comment by MisterNando** [comment]
Another matter of camel case vs. roadkill case.  I'm going to post a new deploy to dev now so we can verify all these.

**Comment by MisterNando** [comment]
This was addressed in the mapping rework, but is not testable using old data.  To verify conclusively, we need a new set of data with new mappings.

**Comment by paynejd** [comment]
Will be difficult (or not possible) to do get the mappings in there until the import script has been modified to support importing mappings. Is that next up?

**Comment by MisterNando** [comment]
Yes, that is next.
