### ISSUE TITLE
OCL import and export formats should be compatible

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/oclapi#82]
The format/syntax used in the exports should be compatible with the format of the exports so that it can be used as a backup and easily imported back into OCL when needed.

**Comment by MisterNando** [comment]
@paynejd , I see you've changed the label from "enhancement" to "question", but the description still reads as an enhancement.  What is the work to be done here?  It looks like it may be beyond the scope we agreed to.

**Comment by paynejd** [comment]
I changed it to question so that we'd remember to discuss and determine if
there is an actual gap here.

--
Jonathan Payne, MS
615.579.5413
skype: jonathandavidpayne

**Comment by paynejd** [comment]
Created new ticket #99 to replace this -- this will potentially get wrapped into future functionality.
