### ISSUE TITLE
Empty mapping field is returned with concept details

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/oclapi#83]
Concept details includes a "mappings_url" field and a "mappings" field. Currently, "mappings" appears to always empty and you must browse to the . For example (see http://dev.openconceptlab.org/orgs/OMRS/sources/OMRS/concepts/32/?debug=1): 

![image](https://cloud.githubusercontent.com/assets/1189689/6097723/fb9a4382-af95-11e4-9711-547975f3bed1.png)

At the API level, you can see this here:
* http://api.dev.openconceptlab.com/v1/orgs/OMRS/sources/OMRS/concepts/32/mappings/
* http://api.dev.openconceptlab.com/v1/orgs/OMRS/sources/OMRS/concepts/32/

Is this by design, a bug, or just a partially implemented feature?

With the new specification for mappings, it will be desirable to be able to return concept details without including any mappings by default but to support optionally return all direct mappings and/or all inverse mappings. Perhaps the best implementation would be to only return mappings if a `includeMappings=true` parameter is added to the query. In that case, `includeInverseMappings=true` would also be supported to include all inverse mappings.

**Comment by MisterNando** [comment]
I'm not sure where this came from - I don't see it anywhere in the spec: https://github.com/OpenConceptLab/oclapi/wiki/concepts

**Comment by paynejd** [comment]
As per our discussions last week, this will be implemented according to this modified spec on the wiki (https://github.com/OpenConceptLab/oclapi/wiki/concepts) and sub-resources will "inherit" the "verbose=true" behavior

**Comment by MisterNando** [comment]
I believe this is done, save for the inheriting of "verbose=true".

**Comment by paynejd** [comment]
I tested this on concept CIELTEST:CIELTEST:995 on dev and the behavior did not work correctly. 

Listing mappings directly under the concept returns 2 results:
* http://api.dev.openconceptlab.com/orgs/CIELTEST/sources/CIELTEST/concepts/995/mappings/

Both concept summary and details include empty mappings list: 
* http://api.dev.openconceptlab.com/orgs/CIELTEST/sources/CIELTEST/concepts/?q=995
* http://api.dev.openconceptlab.com/orgs/CIELTEST/sources/CIELTEST/concepts/995/

**Comment by paynejd** [comment]
Closing this ticket...
