### ISSUE TITLE
Concept details must include the full details (not summaries) of its sub-resources

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/oclapi#84]
When querying concept details, its sub-resources (names, descriptions) must return the detailed formats. For example, the names and descriptions returned by this query do not include "uuid" or "type". "external_uuid" should also be included (once implemented).

http://api.dev.openconceptlab.com/v1/orgs/OMRS/sources/OMRS/concepts/32/

Here's what they should look like:
```
{
   type: "ConceptName"
   uuid: "9f835591e0d247eb838d8b8047b0fd96"
   external_uuid: "1234"
   locale: "en"
   locale_preferred: false
   name: "Peripheral smear for malarial parasites"
   name_type: null
}
{
   type: "ConceptDescription"
   uuid: "f8b47683e4294ddebde7068a90b322bd"
   external_uuid: "5432"
   locale: "en"
   locale_preferred: false
   description: "Peripheral smear study for malarial parasites is the gold standard in diagnosing malarial infection. It involves collection of a blood smear, staining and examination of the the red blood cells for intracellular malarial parasites."
   description_type: null
}
```

**Comment by MisterNando** [comment]
@paynejd , I know we've discussed this enhancement, but I don't see it anywhere in the scope document.  Including this would increase the scope beyond what we agreed to.

**Comment by paynejd** [comment]
the SOW indicates that high priority bugs that we identify need to be
addressed. this is one of the last minute bugs I found during testing.

--
Jonathan Payne, MS
615.579.5413
skype: jonathandavidpayne

**Comment by MisterNando** [comment]
Sorry - I read it as an enhancement (per the label).  I didn't realize we had most of this implemented already.

**Comment by paynejd** [comment]
When viewing concept details (e.g. http://api.dev.openconceptlab.com/orgs/CIELTEST/sources/CIELTEST/concepts/995/) - there is a lingering empty "mappings" list that shows up even if mappings are not included. This should be removed.

When mapping and inverse mappings are included, they are displayed in summary form unless verbose is set to true even though the names and descriptions are displayed in their full details. Is this by design? It seems inconsistent. (see http://api.dev.openconceptlab.com/orgs/CIELTEST/sources/CIELTEST/concepts/995/?includeMappings=true&includeInverseMappings=true&verbose=true)

Finally, when "inverseMappings" is set to true, the inverse maps are added into the "mappings" list. I thought we discussed putting them into a separate list named "inverse_mappings" which is what I wrote in the spec.

**Comment by paynejd** [comment]
@MisterNando this is completed correct?

**Comment by MisterNando** [comment]
This was the comment that prompted the phone call ;-)  Here is what I implemented:

1. By default, the mappings attribute on a concept detail is an empty array.
2. If includeMappings=true, the array will be populated with all mappings FROM this concept within this source.
3. If includeInverseMappings=true, the array will be populated with the above PLUS all mappings TO this concept within this source.
4. The verbose flag DOES apply to the mappings, if they are included.

I'm hoping this is acceptable.

**Comment by paynejd** [comment]
Yes, this is perfect. Will test. Thanks!
