### ISSUE TITLE
New mappings must be support "retired" functionality (same as concepts)

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/oclapi#85]
To fully support OpenMRS, mappings must support the "retired" functionality. This means adding the "retired" field to the mappings resource, and switching the "DELETE" method on mapping to setting "retired=true". Finally, performing "DELETE" with the "?purge=true" parameter will cause a full delete of the resource (rather than just retiring it).

**Comment by MisterNando** [comment]
@paynejd , does this apply to concepts as well?  Also, how do you "un-retire" something?  And what should happen when the user tries to create a resource that "collides" with a retired resource (e.g. a mapping with the same type/from/to)?

**Comment by paynejd** [comment]
How is "un-retiring" done for concepts? The best option I can think of is to do a POST with "retire=false" for a mapping or concept?

Collisions should not be allowed -- if the identical mapping exists but is retired, this is intended to mean that this combination of type/from/to should not be used.

**Comment by paynejd** [comment]
Aaron, is this ticket now complete? How was "un-retiring" implemented?

**Comment by MisterNando** [comment]
Yes.  I'm assuming you meant a PUT with retire=false, as the existing update operation is accomplished via PUT; not POST.
