### ISSUE TITLE
Update API documentation

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/oclapi#86]
Need to review and update the entire documentation, esp. mappings

[Home](https://github.com/OpenConceptLab/oclapi/wiki/Home/)
* Verify that all URL parameters are `camelCase` (esp "sortAsc" and "sortDesc")
* Verify the implementation of "sortAsc" and "sortDesc"
* Verify filters implementation (esp. for more than one option using boolean operators)

[Orgs](https://github.com/OpenConceptLab/oclapi/wiki/orgs/)

[Users](https://github.com/OpenConceptLab/oclapi/wiki/users/)

[Sources](https://github.com/OpenConceptLab/oclapi/wiki/sources/)

[Collections](https://github.com/OpenConceptLab/oclapi/wiki/collections/)

[Concepts](https://github.com/OpenConceptLab/oclapi/wiki/concepts/)

[Mappings](https://github.com/OpenConceptLab/oclapi/wiki/mappings/)

Others...

**Comment by judywawira** [comment]
Thought of auromating the api doc so that it's generated automatically ? At
least the methods and objects

See example of openmrs

On Wednesday, February 11, 2015, Jonathan Payne <notifications@github.com>
wrote:

> Need to review and update the entire documentation, esp. mappings
>
> Home <https://github.com/OpenConceptLab/oclapi/wiki/Home/>
>
>    - Verify that all URL parameters are camelCase (esp "sortAsc" and
>    "sortDesc")
>    - Verify the implementation of "sortAsc" and "sortDesc"
>    - Verify filters implementation (esp. for more than one option using
>    boolean operators) Orgs
>    <https://github.com/OpenConceptLab/oclapi/wiki/orgs/> Users
>    <https://github.com/OpenConceptLab/oclapi/wiki/users/> Sources
>    <https://github.com/OpenConceptLab/oclapi/wiki/sources/> Collections
>    <https://github.com/OpenConceptLab/oclapi/wiki/collections/> Concepts
>    <https://github.com/OpenConceptLab/oclapi/wiki/concepts/> Mappings
>    <https://github.com/OpenConceptLab/oclapi/wiki/mappings/>
>
> Others...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OpenConceptLab/oclapi/issues/86>.
>


-- 
Judy

**Comment by paynejd** [comment]
Complete.
