### ISSUE TITLE
Remove /sources/[src]/ functionality

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/oclapi#89]
Currently, it is possible to do a GET on /sources/[src]/. For example: `GET /sources/OMRS/`

The spec'd behavior is that sources can be searched at the top-level endpoint (e.g. `GET /sources/?q=WHO`), and that individual sources are actually retrieved under their owner (e.g. `GET /orgs/[org]/sources/[src]` OR `GET /users/[user]/sources/[src]/`).

**Comment by MisterNando** [comment]
This has been fixed for a few days now.
