### ISSUE TITLE
create source for an org results in "creator cannot be none"

### ISSUE THREAD

**Issue by pkshiu** [OpenConceptLab/oclapi#91]
From a clean database, try to create the first source after created an org.
Below is the log for the POST and the response:

(logs for this API trace for all calls is found in /var/log/ocl/web_debug.log* on the server)

```
[2015/02/19 21:37:59] DEBUG   : POST http://api.dev.openconceptlab.com/v1/orgs/CIELTEST/sources/ {"website": "", "name"\
: "CIELTEST", "default_locale": "en", "short_code": "CIELTEST", "description": "", "source_type": "Dictionary", "full_n\
ame": "Columbia International eHealth Laboratory (test)", "public_access": "View", "id": "CIELTEST", "supported_locales\
": "en"} {'Content-Type': 'application/json', 'Authorization': u'Token 22f6bf9500958d9a49b4a7c16203c17de3b59d45'}
[2015/02/19 21:37:59] DEBUG   : API /v1/orgs/CIELTEST/sources/
[2015/02/19 21:37:59] DEBUG   : POST RESULT: 400
[2015/02/19 21:37:59] DEBUG   : POST JSON: {
    "creator": "Creator cannot be None."
}
```

**Comment by MisterNando** [comment]
@pkshiu , are you still seeing this?  I just tried it locally and on dev - even using the same token on dev - and it worked.

**Comment by pkshiu** [comment]
Hi, I am seeing it (just tried) on the dev box web interface.
Login: sysadmin
password: password
There is a problem even with the search screen which maybe caused by something else, but I want to create the source first.
goto dev.openconceptlab.org/orgs/CIELTEST
then add a source

Are you saying if you call that API endpoint as I specified above you don't have the problem? Are you using the dev mongo database? or a local one?

The key difference is that the dev mongodb has just been recreated. Your auth keys should NOT work.

**Comment by MisterNando** [comment]
I just ran:

POST http://api.dev.openconceptlab.com/v1/orgs/CIELTEST/sources/

with 

```
{"website": "", "name": "CIELTEST3", "default_locale": "en", "short_code": "CIELTEST3", "description": "", "source_type": "Dictionary", "full_name": "Columbia International eHealth Laboratory (test)", "public_access": "View", "id": "CIELTEST3", "supported_locales": "en"}
```

(I'd previously created CIELTEST1 and CIELTEST2)

Using this token: 22f6bf9500958d9a49b4a7c16203c17de3b59d45

And it worked all 3 times.

**Comment by MisterNando** [comment]
Wait, is there a difference between the .org and the .com?

**Comment by pkshiu** [comment]
OK this is very strange. .com and .org should go to the same place (at least when I tried.)
I looked into the database and see the new sources you created.
Why couldn't I create them on the website side?

**Comment by MisterNando** [comment]
Dunno.  Is there some caching going on?

**Comment by pkshiu** [comment]
I just tried this and it worked now. The only different is that solr was down and index was not rebuilt. Do you think that could have caused it?
