### ISSUE TITLE
How can I tell if a member is an administrative member of an organization via the API?

### ISSUE THREAD

**Issue by pkshiu** [OpenConceptLab/oclapi#98]
This is required to do better permission/display of CRUD operations for organization.

**Comment by paynejd** [comment]
See comment on #65

**Comment by paynejd** [comment]
This functionality is not part of the spec for this phase -- users are either members or they are not. The only differentiation is possibly in the user set in the "created_by" field.

**Comment by paynejd** [comment]
Closed - replaced with #100 - assigned to future functionality
